### ISSUE TITLE
[Bug] Nesting Wildcards

### ISSUE THREAD

**Issue by Miyuutsu** [adieyal/sd-dynamic-prompts#117]
Trying to use nesting is breaking the entire extension for me. 

**To Reproduce**
1. Put a nested prompt into positive containing wildcards. For example: `{__season__,__outdoor__,__time__|__indoor__,__time__}`
2. Click on `Generate`.
3. See error.

**Expected behaviour**
It should process both wildcards and the nested prompts.

**Additional context**
```Error running process: /home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/home/miyuu/stable-diffusion-webui/modules/scripts.py", line 338, in process
    script.process(p, *script_args)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 409, in process
    all_prompts = generator.generate(num_images)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 203, in generate
    all_prompts = [self.generate_prompt(self._template) for _ in range(num_prompts)]
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 203, in <listcomp>
    all_prompts = [self.generate_prompt(self._template) for _ in range(num_prompts)]
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 194, in generate_prompt
    prompt = self.pick_variant(old_prompt)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 179, in pick_variant
    return re_combinations.sub(lambda x: self._replace_combinations(x), template)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 179, in <lambda>
    return re_combinations.sub(lambda x: self._replace_combinations(x), template)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 158, in _replace_combinations
    collected = collector.collect((low_range, high_range))
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 75, in collect
    picked = self._selector.pick()[0]
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 41, in pick
    picked.append(self._random.choice(option))
  File "/usr/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

I have only been able to reproduce this while using the same wildcards nested. So for example if I simply have `{__indoor__|__outdoor__}` it works fine but `{__indoor__|__indoor__,cat}` will break. When this occurs it fails to process all wildcards in the prompt, even those not nested. However if I was to do `{__indoor__|__outdoor__},__indoor__` it would work fine, so it seems unrelated to using the same wildcard twice outside of nesting purposes. I assume contents of wildcards doesn't matter since I can reproduce this even with wildcards with two random items in them but if necessary I can provide some.

Furthermore it seems I'm only able to reproduce this on certain seeds. For example I have been able to reproduce it on `3714`. Despite this selecting "Unlink Seed From Prompt" does not resolve the issue.

**Comment by adieyal** [comment]
Thanks for reporting this. I'll look into it, but only in a few days

**Comment by adieyal** [comment]
Could you please test the latest version -  v1.4.1?

**Comment by Miyuutsu** [comment]
Thanks! It does appear to be fixed now! The only thing I would say is there seems to be a new minor issue. With every generation with the script enabled I'm now seeing `INFO:dynamic_prompting.py:Prompt matrix will create 1 images in a total of 1 batches.` regardless of whether I'm using any wildcards or functionality. I don't believe it has any actual impact however and I haven't the time right now to do a lot of testing but otherwise seems fine.
