### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by yami-no-tusbas** [adieyal/sd-dynamic-prompts#118]
**Describe the bug**
It did not work at all, was working before.

**To Reproduce**

1. Generate an image using dynamic prompt with magic prompt, wathever settings.
2. Enjoy your image, see the console...

- [x] Dynamic Prompts enabled
- [x] Magic prompt (L:291,C0.9)
- [x] Disable negative prompt

**Expected behaviour**
Just create the dynamic prompt and work...

**Additional context**

Here is the log : 
```
Error running process: D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1093, in _get_module
  File "D:\Python_3.10.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers.models.bloom.configuration_bloom'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 338, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 378, in process
    generator = self._create_generator(
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 177, in _create_generator
    generator = MagicPromptGenerator(
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generators\magicprompt.py", line 44, in __init__
    self._generator = self._load_pipeline()
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generators\magicprompt.py", line 27, in _load_pipeline
    model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 461, in from_pretrained
    The model to register.
  File "D:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 607, in keys
    ]
  File "D:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 608, in <listcomp>
    return mapping_items + list(self._extra_content.items())
  File "D:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 604, in _load_attr_from_module
    )
  File "D:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in getattribute_from_module
    self._config_mapping = config_mapping
  File "D:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1083, in __getattr__
  File "D:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1095, in _get_module
RuntimeError: Failed to import transformers.models.bloom.configuration_bloom because of the following error (look up to see its traceback):
No module named 'transformers.models.bloom.configuration_bloom'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.86it/s]
{"prompt": "1girl cosmic horror cthulhu mythos", "all_prompts": ["1girl cosmic horror cthulhu mythos"], "negative_prompt": "", "all_negative_prompts": [""], "seed": 3063535030, "all_seeds": [3063535030], "subseed": 1588994582, "all_subseeds": [1588994582], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "Euler a", "cfg_scale": 7, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "1a7df6b8", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["1girl cosmic horror cthulhu mythos\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3063535030, Size: 512x512, Model hash: 1a7df6b8, Model: Anything-V3.0-pruned-fp32, Clip skip: 2"], "styles": ["None", "None"], "job_timestamp": "20221217102750", "clip_skip": 2, "is_using_inpainting_conditioning": false}
```

**Comment by adieyal** [comment]
That's a strange error. Could you please have a look in prompts/generators/magicprompt.py on line 12, you should see something like `MODEL_NAME =... `

Could you please paste the entire line here?

**Comment by yami-no-tusbas** [comment]
line 12 : `MODEL_NAME = "Gustavosta/MagicPrompt-Stable-Diffusion"`

**Comment by adieyal** [comment]
Is this still an issue for you? I haven't been able to reproduce the error.

**Comment by yami-no-tusbas** [comment]
Well it happens time to time still, but it's another error this one as not apparead again.
