### ISSUE TITLE
[Bug] Wildcards broken since [a122279] when preceded by a comma.

### ISSUE THREAD

**Issue by Miyuutsu** [adieyal/sd-dynamic-prompts#145]
I wish I could provide more information other than "broken" but I don't get any errors or anything, it just simply fails to process any wildcards since a122279. I figure this would be pretty big and noticed quite quickly so it wouldn't shock me at all if it's my end for some reason. I've confirmed that it's broken in every commit since and the last working commit is f7ac537. I've confirmed this both with a variety of wildcards as well as a single wildcard with two items to choose from. I know you had a lot going on with that one so if there's anything I can provide to narrow this down, please let me know.

**Comment by adieyal** [comment]
Yeah, https://github.com/adieyal/sd-dynamic-prompts/commit/a12227915738da9b816669bebe88523b88ec19fb was pretty big. I've been working on mopping up all the edge cases. To narrow down the issue, could you do the following

1. Make sure that there is a wildcards file in the wildcards directory, e.g. colours.txt, or whatever
2. Try a simple prompt like `A __colours__ rose`
3. If there isn't any output, could you look in the terminal and copy and paste any errors that you might see.

There have been quite a few issues with this latest release, but wildcards seem to work fine.

**Comment by Miyuutsu** [comment]
So since that worked I messed around with it a little bit more. I did exactly what you said and did `A __colours__ rose` with only a `colours.txt` that contained colors red, blue and yellow, and it worked fine. I have however been able to determine that commas seem to break the following wildcard. So for example if I have the aforementioned `__colours__` and one I called `animal.txt` containing cat and dog, if I have `__colours__ __animal__` then it works fine, `__colours__,__animal__` will break `__animal__` while `__colours__, __animal__` seems to work fine as well. The image is output fine, but it seems to not recognize the wildcard when preceded by a comma and will simply use text itself as a prompt, no errors in log.

**Comment by Miyuutsu** [comment]
Also I've caught another one for you. Seems related to the new whitespace fix 8d06ee7 and is present in 7811b04. Wildcard containing:

1. `:3`
2. `:<`
3. `:>`
4. `:c`

Returns without fail:
```
Error running process: /home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/home/miyuu/stable-diffusion-webui/modules/scripts.py", line 338, in process
    script.process(p, *script_args)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 412, in process
    all_prompts = generator.generate(num_images)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 231, in generate
    prompts = self._generator.generate_prompts(self._template, max_prompts)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 123, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 19, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 19, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/commands.py", line 19, in get_prompt
    prompts = list(self.prompts())
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 33, in prompts
    prompts = generator.generate_prompts(val, 1)
  File "/home/miyuu/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 124, in generate_prompts
    generated_prompts.append(squash_whitespace(prompts[0]))
IndexError: list index out of range
```


I'm guessing the `:`?

**Comment by adieyal** [comment]
Are you using v1.5.15?  If not, could you upgrade and try again?

**Comment by Miyuutsu** [comment]
Sorry to say but I do not use github as much as I really should, I am not sure if I'm on v1.5.15 or not. I went ahead and reinstalled the latest master just to be sure since it's possible checking out different versions messed something up earlier and the last issue I reported is no longer present, but having a comma prior to a wildcard still causes it to not parse.

**Comment by adieyal** [comment]
I've tested the latest version with your examples. It seems to parse correctly. Could you please check and let me know?

**Comment by Miyuutsu** [comment]
Confirmed working now. Thank you! I can say without a doubt that this extension of yours is easily the one I use the most, so keep up the great work!
