### ISSUE TITLE
DP stops working after some succesful runs - not selecting text inside {} or using wildcards

### ISSUE THREAD

**Issue by manzomium** [adieyal/sd-dynamic-prompts#163]
**Describe the bug**
It works as intended for some runs, then it stops working and show this error message:

Error running process: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 347, in process
    script.process(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/dynamic-prompts/scripts/dynamic_prompting.py", line 301, in process
    all_prompts = generator.generate(original_prompt, num_images)
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/generators/randomprompt.py", line 39, in generate
    prompts = self._generator.generate_prompts(template, num_images)
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 137, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 26, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 26, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/commands.py", line 20, in get_prompt
    prompts = list(self.prompts())
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 44, in prompts
    prompts = generator.generate_prompts(val, 1)
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 141, in generate_prompts
    prompt = prompts[0]
IndexError: list index out of range

**To Reproduce**
Run some batches, and it stops working after the third batch

**Are you using a local install or a colab?**
Colab, AUTO1111/LastBen

**Expected behaviour**
To keep running as intended, and chose text inside {} and from wildcards

**Additional context**
Installed DP via a command line in Colab
The final prompt in PNG info shows all text inide the {}, ie: Image of a {blue|red} ball on __colors__ background
Token count is 74/75, if relevant

**Comment by manzomium** [comment]
Now it won't work at all, even after reloading the colab... :-(

**Comment by adieyal** [comment]
what was the prompt that broke it?

**Comment by adieyal** [comment]
and when you say not working after restarting the colab - do you get an error message?

**Comment by manzomium** [comment]
> and when you say not working after restarting the colab - do you get an error message?

yes, this one. I did everything I did when I made it work...

Error running process: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 347, in process
    script.process(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/dynamic-prompts/scripts/dynamic_prompting.py", line 301, in process
    all_prompts = generator.generate(original_prompt, num_images)
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/generators/randomprompt.py", line 39, in generate
    prompts = self._generator.generate_prompts(template, num_images)
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 137, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 26, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 26, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/commands.py", line 20, in get_prompt
    prompts = list(self.prompts())
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 44, in prompts
    prompts = generator.generate_prompts(val, 1)
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/parser/random_generator.py", line 141, in generate_prompts
    prompt = prompts[0]
IndexError: list index out of range


> what was the prompt that broke it?

something like this

(((shackles))), (((naked))) ((({30|40} years old))) __Nati/europe__ ((concubine)), __time/10-50-decades__, ((shy face)), [pubic hair], (({standing|sitting} in rich imperial {living room|spa})), (jewels), natural light, ((35mm)), by __artists/Photography/photographers__

btw, it seems that the wildcard __allphotographers__ cannot be found in the photographers directory. I removed it manually from the list

**Comment by adieyal** [comment]
I made slight changes to your prompt so that I  could test it with the wildcards the come bundled with the extension

`{iron|golden|silver|copper} (((shackles))), ((({30|40} years old))) __people/nationalities/central-europe__ ((concubine)), __time/decade__, ((shy face)), (({standing|sitting} in rich imperial {living room|spa})), (jewels), natural light, ((35mm)), by __artists/Photography/photographers__`

I works fine for me. Do you have the most up-to-date version of Dynamic Prompts?

btw, where is the reference to `__allphotographers__`?

**Comment by manzomium** [comment]
thanks for checking, I'll try that again and see if it keeps working. As said, it worked when I used it first, then it stopped working at the second batch. Could you get any useful info from the error message?

Re __all_photographers__, it is a reference inside the photographers.txt (__artists/Photography/by_country/all_photographers__) in your jumbo collection. I guess DP picked it while running wildcards but didn't find an all_photographers wildcard - I couldn't either

**Comment by adieyal** [comment]
I'm not sure what caused it to break - I have in the meantime added some logic that will handle the situation more gracefully rather than just die. Let me know if it happens again 

> Re all_photographers, it is a reference inside the photographers.txt

Thanks, found it and fixed it

**Comment by manzomium** [comment]
it works just fine now :-) yayyyy
thanks a world
