### ISSUE TITLE
Does not install in Automatic 1111 GUI

### ISSUE THREAD

**Issue by Taikakim** [adieyal/sd-dynamic-prompts#164]
I  installed from the GUI, and upon reload of the UI I got an error message.

The Last Ben's Automatic 1111

```
Error running install.py for extension /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts.
Command: "/usr/bin/python3" "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/install.py", line 12, in <module>
    import launch
ModuleNotFoundError: No module named 'launch'


Closing server running on port: 7860
Restarting UI...
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 15, in <module>
    from dynamicprompts.wildcardmanager import WildcardManager
ModuleNotFoundError: No module named 'dynamicprompts'
```

**Comment by adieyal** [comment]
Please see the troubleshooting section here: [https://github.com/adieyal/sd-dynamic-prompts#troubleshooting](https://github.com/adieyal/sd-dynamic-prompts#troubleshooting) - I'm closing this issue, but re-open it if the suggestion there doesn't work

**Comment by Taikakim** [comment]
Oops, didn't notice this, my bad. Yes this seems to help, thank you!

**Comment by Taikakim** [comment]
I do get this now though:

```
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 23, in <module>
    from prompts.generator_builder import GeneratorBuilder
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generator_builder.py", line 21, in <module>
    class GeneratorBuilder:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generator_builder.py", line 98, in GeneratorBuilder
    unlink_seed_from_prompt=constants.UNLINK_SEED_FROM_PROMPT,
AttributeError: module 'dynamicprompts.constants' has no attribute 'UNLINK_SEED_FROM_PROMPT'
```

**Comment by adieyal** [comment]
Looks like you have a slightly older version - try downloading an update

**Comment by Taikakim** [comment]
I downloaded just now the latest version of the Automatic 1111 notebook, and I get this error when running that pip command:

It's weird since in the morning this worked... I don't understand your suggestion, do you mean, remove the extension and re-install it? I just installed it this morning so it should be quite new.

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting dynamicprompts
  Downloading dynamicprompts-0.2.5-py3-none-any.whl (23 kB)
Collecting requests<3.0.0,>=2.28.1
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 9.1 MB/s eta 0:00:00
Collecting jinja2<4.0.0,>=3.1.2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 KB 19.0 MB/s eta 0:00:00
Requirement already satisfied: tqdm<5.0.0,>=4.64.1 in /usr/local/lib/python3.8/dist-packages (from dynamicprompts) (4.64.1)
Requirement already satisfied: pyparsing<4.0.0,>=3.0.9 in /usr/local/lib/python3.8/dist-packages (from dynamicprompts) (3.0.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from jinja2<4.0.0,>=3.1.2->dynamicprompts) (2.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.28.1->dynamicprompts) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.28.1->dynamicprompts) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.28.1->dynamicprompts) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.28.1->dynamicprompts) (2.10)
Installing collected packages: requests, jinja2, dynamicprompts
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 2.11.3
    Uninstalling Jinja2-2.11.3:
      Successfully uninstalled Jinja2-2.11.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
notebook 5.7.16 requires jinja2<=3.0.0, but you have jinja2 3.1.2 which is incompatible.
flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.
clean-fid 0.1.31 requires requests==2.25.1, but you have requests 2.28.1 which is incompatible.
Successfully installed dynamicprompts-0.2.5 jinja2-3.1.2 requests-2.28.1
```

**Comment by Taikakim** [comment]
Yupp it was updated meanwhile, updating and applying changes fixed this.
