### ISSUE TITLE
AttributeError: module 'dynamicprompts.constants' has no attribute 'UNLINK_SEED_FROM_PROMPT'

### ISSUE THREAD

**Issue by Salient0ne** [adieyal/sd-dynamic-prompts#168]
I just installed this extension not able to get it working, I use python 3.10.8 and automatic is up to date

Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 23, in <module>
    from prompts.generator_builder import GeneratorBuilder
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generator_builder.py", line 21, in <module>
    class GeneratorBuilder:
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generator_builder.py", line 98, in GeneratorBuilder
    unlink_seed_from_prompt=constants.UNLINK_SEED_FROM_PROMPT,
AttributeError: module 'dynamicprompts.constants' has no attribute 'UNLINK_SEED_FROM_PROMPT'

**Comment by adieyal** [comment]
please update and try again

**Comment by Salient0ne** [comment]
seems to be working now, thank you very much. This is exactly what i was looking for :)
