### ISSUE TITLE
Plugin broken on newest Automatic1111 commit

### ISSUE THREAD

**Issue by r0buster** [adieyal/sd-dynamic-prompts#180]
**Describe the bug**

Running the plugin with the latest AUTOMATIC1111 update results in this error, maybe because of the separation of the inpainting tab?

```
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "C:\Apps\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 872, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Apps\stable-diffusion-webui\venv\lib\site-packages\transformers\pipelines\__init__.py", line 48, in <module>
    from .fill_mask import FillMaskPipeline
  File "C:\Apps\stable-diffusion-webui\venv\lib\site-packages\transformers\pipelines\fill_mask.py", line 12, in <module>
    from ..tf_utils import stable_softmax
  File "C:\Apps\stable-diffusion-webui\venv\lib\site-packages\transformers\tf_utils.py", line 26, in <module>
    def shape_list(tensor: Union[tf.Tensor, np.ndarray]) -> List[int]:
AttributeError: module 'tensorflow' has no attribute 'Tensor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Apps\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Apps\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Apps\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 25, in <module>
    from prompts.generator_builder import GeneratorBuilder
  File "C:\Apps\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generator_builder.py", line 14, in <module>
    from dynamicprompts.generators.magicprompt import MagicPromptGenerator
  File "C:\Apps\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\magicprompt.py", line 17, in <module>
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Apps\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 862, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Apps\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 874, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
module 'tensorflow' has no attribute 'Tensor'
```

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Update to latest on Automatic1111
2. Enable plugin
3. Start webui-user.bat

Also mention which checkboxes have been set.

**Are you using a local install or a colab?**

Local

**Expected behaviour**
It currently breaks generation entirely.

**Comment by adieyal** [comment]
Can you try to delete your magic prompt model and re-download? On my machine it's here: $HOME/.cache/huggingface/hub/models--Gustavosta--MagicPrompt-Stable-Diffusion

**Comment by r0buster** [comment]
I do not seem to have such a folder. These are the only ones in the hub:

```
models--FredZhang7--distilgpt2-stable-diffusion-v2
models--bert-base-uncased
models--distilgpt2
models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K
models--openai--clip-vit-large-patch14
```

I tried renaming the folder and starting the webui-user, but without any luck.

**Comment by adieyal** [comment]
Have a look at this issue - I think it's related: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6179

**Comment by r0buster** [comment]
Yes, that did the trick. Not sure if it was related to dreambooth (never had it enabled, just downloaded) but I tried deleting a few directories like one of the posters suggested. 

Thanks for your help.
