### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Panchvzluck** [adieyal/sd-dynamic-prompts#197]
**Describe the bug**
When using the latest commit from the webui https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f53527f7786575fe60da0223bd63ea3f0a06a754 and latest commit of dynamic prompts https://github.com/adieyal/sd-dynamic-prompts/commit/401682b06e80db8b307b9650f6e4e201dfd2a8d9, you get list index out of range with any prompt.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Open latest webui.
2. Put any prompt.
3. Get `IndexError: list index out of range`
4. Next error with complete CMD
![image](https://user-images.githubusercontent.com/19153797/213882911-6282baef-7cbc-4dd9-8208-46df1de1c275.png)

```
Error completing request
Arguments: ('task(0r2b32s2gt80byh)', 'test', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, False, False, False, False, '', 1, '', 0, '', True, False, False) {}

Traceback (most recent call last):

  File "G:\Stable difussion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
    
  File "G:\Stable difussion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
    
  File "G:\Stable difussion\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
    processed = process_images(p)
    
  File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 475, in process_images
    res = process_images_inner(p)
    
  File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 574, in process_images_inner
    file.write(processed.infotext(p, 0))
    
  File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 327, in infotext
    return create_infotext(p, self.all_prompts, self.all_seeds, self.all_subseeds, comments=[], position_in_batch=index % self.batch_size, iteration=index // self.batch_size)
    
  File "G:\Stable difussion\stable-diffusion-webui\modules\processing.py", line 457, in create_infotext
    negative_prompt_text = "\nNegative prompt: " + p.all_negative_prompts[index] if p.all_negative_prompts[index] else ""
IndexError: list index out of range

```

Local installation, tried on both old and clean webui installation.

**Expected behaviour**
Prompts to work.

**Additional context**
Tried on new clean installation with the newest commit, just added one model and same issue persists.
When disabling dynamic prompts, or uninstalling the extensions, prompts works as they should.

**Comment by ArrowM** [comment]
dup of #195
