### ISSUE TITLE
webui update introduces breaking changes?

### ISSUE THREAD

**Issue by khushil** [adieyal/sd-dynamic-prompts#207]
**Describe the bug**
After a git pull this morning I get the following:

SD-Webui API layer loaded
Error calling: G:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py/ui
Traceback (most recent call last):
  File "G:\AI\stable-diffusion-webui\modules\scripts.py", line 232, in wrap_call
    res = func(*args, **kwargs)
  File "G:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 129, in ui
    WILDCARD_DIR=wildcard_manager.path,
AttributeError: 'WildcardManager' object has no attribute 'path'

Error calling: G:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py/ui
Traceback (most recent call last):
  File "G:\AI\stable-diffusion-webui\modules\scripts.py", line 232, in wrap_call
    res = func(*args, **kwargs)
  File "G:\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 129, in ui
    WILDCARD_DIR=wildcard_manager.path,
AttributeError: 'WildcardManager' object has no attribute 'path'

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. git pull webui (AUTOMATIC1111)
2. launch webui

**Are you using a local install or a colab?**

local install

**Expected behaviour**

Should load without the breaks

**Additional context**

none but happy to help debug

**Comment by adieyal** [comment]
could you try running `venv/bin/python -m pip install dynamicprompts==0.3.2` from within your webui directory and let me know if that fixes it?

**Comment by dimitri-vs** [comment]
@adieyal Had a similar error message and this fixed it for me.

**Comment by adieyal** [comment]
Thanks for confirming. Not sure why the new version wasn't being installed

**Comment by adieyal** [comment]
@dimitri-vs, @khushil - could you please check whether this is fixed?

**Comment by ososoba** [comment]
I'm running into this issue as well with a fresh install of Automatic1111

`Error running install.py for extension extensions\dynamic-prompts.
Command: "D:\Stable Diffusion\1. Stable Diffusion Program\venv\Scripts\python.exe" "extensions\dynamic-prompts\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "D:\Stable Diffusion\1. Stable Diffusion Program\extensions\dynamic-prompts\install.py", line 4, in <module>
    from dynamicprompts.utils import is_empty_line
ModuleNotFoundError: No module named 'dynamicprompts'


Error running install.py for extension extensions\sd-dynamic-prompts.
Command: "D:\Stable Diffusion\1. Stable Diffusion Program\venv\Scripts\python.exe" "extensions\sd-dynamic-prompts\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "D:\Stable Diffusion\1. Stable Diffusion Program\extensions\sd-dynamic-prompts\install.py", line 4, in <module>
    from dynamicprompts.utils import is_empty_line
ModuleNotFoundError: No module named 'dynamicprompts'


Launching Web UI with arguments: --xformers --opt-channelslast
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "D:\Stable Diffusion\1. Stable Diffusion Program\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Stable Diffusion\1. Stable Diffusion Program\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\Stable Diffusion\1. Stable Diffusion Program\extensions\dynamic-prompts\scripts\dynamic_prompting.py", line 10, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
ModuleNotFoundError: No module named 'dynamicprompts'

Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "D:\Stable Diffusion\1. Stable Diffusion Program\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Stable Diffusion\1. Stable Diffusion Program\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\Stable Diffusion\1. Stable Diffusion Program\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 10, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
ModuleNotFoundError: No module named 'dynamicprompts'`

I tried `python -m pip install dynamicprompts==0.3.2` from the webui directory and got `Successfully installed dynamicprompts-0.3.2` but the issue persists

**Comment by adieyal** [comment]
Can you please update to the latest version? This issue should be resolved.

**Comment by ososoba** [comment]
It's fixed! Thank you

**Comment by adieyal** [comment]
That's great!
