### ISSUE TITLE
Not starting. 

### ISSUE THREAD

**Issue by Maelstrom2014** [adieyal/sd-dynamic-prompts#238]
Here is error: 
Restarting UI...
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 10, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/generators/__init__.py", line 7, in <module>
    from dynamicprompts.generators.jinjagenerator import JinjaGenerator
  File "/usr/local/lib/python3.8/dist-packages/dynamicprompts/generators/jinjagenerator.py", line 11, in <module>
    from jinja2.ext import Extension
  File "/usr/local/lib/python3.8/dist-packages/jinja2/ext.py", line 17, in <module>
    from .utils import pass_context
ImportError: cannot import name 'pass_context' from 'jinja2.utils' (/usr/local/lib/python3.8/dist-packages/jinja2/utils.py)

**Comment by akx** [comment]
You probably have an old version of `jinja2` installed. Try `pip install -U jinja2`.

**Comment by adieyal** [comment]
@Maelstrom2014 have you resolved this?

**Comment by Maelstrom2014** [comment]
Yes, i reinstalled everything.

чт, 9 февр. 2023 г., 20:21 Adi Eyal ***@***.***>:
