### ISSUE TITLE
Error: Using Prompt Magic

### ISSUE THREAD

**Issue by medledan** [adieyal/sd-dynamic-prompts#251]
**Describe the bug**

Generating Magic Prompts:   0%|                                                                  | 0/1 [00:00<?, ?it/s]Error running process: G:\stable-diffusion-webui-current\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "G:\stable-diffusion-webui-current\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "G:\stable-diffusion-webui-current\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 405, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "G:\stable-diffusion-webui-current\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 87, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts)
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\dynamicprompts\generators\magicprompt.py", line 144, in generate
    return [
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\dynamicprompts\generators\magicprompt.py", line 145, in <listcomp>
    self._generate_magic_prompt(prompt)
  File "G:\stable-diffusion-webui-current\venv\lib\site-packages\dynamicprompts\generators\magicprompt.py", line 152, in _generate_magic_prompt
    prompt = self._generator(
TypeError: 'NoneType' object is not callable

**To Reproduce**
Steps to reproduce the behavior, including the prompt you used if applicable:
1. Selected Prompt Magic [x]
2. Prompt length 50
3. Creativity 0.7
4. Generate
Model: Gustavosta/MagicPrompt-Stable-Diffusion

Also mention which checkboxes have been set.

Dynamic Prompts enabled[x]
Magic Prompt [x]
Dont apply to negative prompts[x]

**Are you using a local install or a colab?**

Local

**Expected behavior**
This is the first time using\running this. Expected an output like the documentation. A random creative prompt output. 

**Additional context**

**Comment by adieyal** [comment]
Is it possible to re-create? When you restart webui, do you still need to change models for it to work again?

**Comment by medledan** [comment]
> Is it possible to re-create? When you restart webui, do you still need to change models for it to work again?

So far its been working just fine. Swapped between models, and have no longer received an error message.

**Comment by adieyal** [comment]
Re-open this issue if it happens again
