### ISSUE TITLE
TypeError: CombinatorialPromptGenerator.__init__() got an unexpected keyword argument 'parser_config'

### ISSUE THREAD

**Issue by PeterTemps** [adieyal/sd-dynamic-prompts#255]
`Error running process: /home/piotr/VsCode/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/home/piotr/VsCode/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/home/piotr/VsCode/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 408, in process
    generator = generator_builder.create_generator()
  File "/home/piotr/VsCode/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/generator_builder.py", line 149, in create_generator
    generator = self.create_basic_generator()
  File "/home/piotr/VsCode/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/generator_builder.py", line 177, in create_basic_generator
    prompt_generator = CombinatorialPromptGenerator(
TypeError: CombinatorialPromptGenerator.__init__() got an unexpected keyword argument 'parser_config'
`

I've been getting this error for few days now. Any idea how to fix it ?

**Comment by adieyal** [comment]
Could you please try to manually update the dynamicprompts library?
From the extensions folder:

```bash
venv/bin/python -m pip install dynamicprompts==0.7.0
```

Did you restart webui after you updated?

**Comment by PeterTemps** [comment]
no didn't work :(. 

I closed the webui, activated venv, used the pip command, launched webui and still the same error.

**Comment by adieyal** [comment]
What is the output of 
```

**Comment by adieyal** [comment]
found the bug - will post an update in a few minutes

**Comment by adieyal** [comment]
Can you test it and let me know if it works?

**Comment by joetech** [comment]
Works with the update.  Thanks!
