### ISSUE TITLE
The Last Ben´s colab is broken if I add this extension

### ISSUE THREAD

**Issue by elBlacksmith** [adieyal/sd-dynamic-prompts#257]
**Describe the bug**
I am using [TLB Colab](https://github.com/TheLastBen/fast-stable-diffusion), and the instalation of this extension causes that I am unable to start the Colab.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. i delete all the old folders and files of the "sd" folder at the root of my Google Drive. 
2. I execute TLB Colab, all the steps. Using the 1.5 version of Stable Difussion. It´s a fresh start.
3. I go tho the Automatic1111 "extension tab, and I add the extension, installing it from the URL. I click the "apply and restart" button on the "extension tab". I do not install anything else before that.
4. I  stop the Colab /Because otherwise the GUI will no restart)
5. I get the error code of below. Unable to start the GUI.
6. It doesn´t matter that I stop completely the colab, deleting the Colab´s temporary files. The error appears again.

Also mention which checkboxes have been set.

**Are you using a local install or a colab?**
Colab

If a colab, which one?
https://github.com/TheLastBen/fast-stable-diffusion

**Expected behaviour**
The A1111 GUI starts and I am able to produce pictures.

**Additional context**

This is the error message shown on the colab website:
```
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 7, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/imports.py", line 153, in <module>
    _TORCHTEXT_LEGACY: bool = _TORCHTEXT_AVAILABLE and _compare_version("torchtext", operator.lt, "0.11.0")
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/imports.py", line 71, in _compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/usr/local/lib/python3.8/dist-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/usr/local/lib/python3.8/dist-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.8/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
```

**Comment by elBlacksmith** [comment]
Also this problem happens with the Colabs at https://github.com/camenduru/stable-diffusion-webui-colab
I guess this is not an issue of the latest Automatic1111 GUI because Camenduru uses a previos version of A1111 (I guess that a more stable one). In that case the error message after the instalation is:

```
Loading weights [1a97f4ef] from /content/stable-diffusion-webui/models/Stable-diffusion/Elysium_Anime_V3.safetensors
Applying xformers cross attention optimization.
Model loaded.
Traceback (most recent call last):
  File "launch.py", line 303, in <module>
    start()
  File "launch.py", line 294, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 139, in webui
    shared.demo = modules.ui.create_ui()
  File "/content/stable-diffusion-webui/modules/ui.py", line 639, in create_ui
    modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "/content/stable-diffusion-webui/modules/scripts.py", line 235, in initialize_scripts
    script = script_class()
  File "/content/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 125, in __init__
    callbacks.register_on_infotext_pasted(self._pnginfo_saver)
  File "/content/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/callbacks.py", line 66, in register_on_infotext_pasted
    script_callbacks.on_infotext_pasted(on_infotext_pasted)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_infotext_pasted'
```

**Comment by adieyal** [comment]
> Also this problem happens with the Colabs at https://github.com/camenduru/stable-diffusion-webui-colab I guess this is not an issue of the latest Automatic1111 GUI because Camenduru uses a previos version of A1111 (I guess that a more stable one). The main difference between TLB and Camenduru is that Camenduru doesn´t connect with Google Drive, so all new execution is from a fresh start.
> 
> In that case the error message after the instalation is:
> 
> ```
> Loading weights [1a97f4ef] from /content/stable-diffusion-webui/models/Stable-diffusion/Elysium_Anime_V3.safetensors
> Applying xformers cross attention optimization.
> Model loaded.
> Traceback (most recent call last):
>   File "launch.py", line 303, in <module>
>     start()
>   File "launch.py", line 294, in start
>     webui.webui()
>   File "/content/stable-diffusion-webui/webui.py", line 139, in webui
>     shared.demo = modules.ui.create_ui()
>   File "/content/stable-diffusion-webui/modules/ui.py", line 639, in create_ui
>     modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
>   File "/content/stable-diffusion-webui/modules/scripts.py", line 235, in initialize_scripts
>     script = script_class()
>   File "/content/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 125, in __init__
>     callbacks.register_on_infotext_pasted(self._pnginfo_saver)
>   File "/content/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/callbacks.py", line 66, in register_on_infotext_pasted
>     script_callbacks.on_infotext_pasted(on_infotext_pasted)
> AttributeError: module 'modules.script_callbacks' has no attribute 'on_infotext_pasted'
> ```

Do you know which version of auto1111 is being used? on_infotext_pasted is definitely there. See here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/script_callbacks.py#L311

**Comment by adieyal** [comment]
I'm going to look into the torch issue over the weekend - see this issue - https://github.com/adieyal/sd-dynamic-prompts/issues/208

**Comment by elBlacksmith** [comment]
@adieyal Uh, sorry, right now I'm tired and I don't remember correctly.

Camenduru allows you to use the latest Automatic1111 if you select the 2.0 branch: https://github.com/camenduru/stable-diffusion-webui/blob/v2.0/modules/script_callbacks.py
If not, it uses the 1.6 version: https://github.com/camenduru/stable-diffusion-webui/blob/v1.6/modules/script_callbacks.py

I think that I used the 1.6, but I was doing other tests and now I'm not sure if it was 1.6 or 2.0.

If you need I can try tomorrow to reproduce the error.

**Comment by akx** [comment]
Closing as stale.
