### ISSUE TITLE
Incorrect parsing of prompt with lora tags

### ISSUE THREAD

**Issue by KondPa** [adieyal/sd-dynamic-prompts#269]
**Describe the bug**
If lora name with double underscore in it is used than dynamic prompt throws error

**To Reproduce**
use prompt with lora that has double underscore in it
"1girl, __clothing__ , <lora:tama5___StyleLora_v10:0.7>"

**Are you using a local install or a colab?**

local install

**Expected behaviour**
Expected to ignore lora while parsing prompt since it doesn't use closing __ in it

**Additional context**
Error running process: F:\AI_art\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "F:\AI_art\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "F:\AI_art\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 423, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "F:\AI_art\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 84, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts)
  File "F:\AI_art\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 47, in generate
    return list(self._sampler.generate_prompts(template, num_images))
  File "F:\AI_art\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\samplers\base.py", line 50, in generate_prompts
    command = parse(prompt, parser_config=self._parser_config)
  File "F:\AI_art\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 257, in parse
    tokens = create_parser(parser_config=parser_config).parse_string(
  File "F:\AI_art\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 63), (line:1, col:64)

**Comment by adieyal** [comment]
There's a PR that will be merged soon that will fix this: https://github.com/adieyal/dynamicprompts/pull/35

**Comment by adieyal** [comment]
v2.8.2 allows you to customise the wildcard prefix and suffix. Have a look in Settings under Dynamic Prompts
