### ISSUE TITLE
I can't use wildcard prompt

### ISSUE THREAD

**Issue by kkmw15** [adieyal/sd-dynamic-prompts#282]
First, I am writing a sentence as a translator as a non-English speaking user. Thank you for your understanding.

Wildcards don't work with characters like:

Error running process: C:\WEBUI0.65.1\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "C:\WEBUI0.65.1\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\WEBUI0.65.1\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 412, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "C:\WEBUI0.65.1\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 73, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts)
  File "C:\WEBUI0.65.1\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 47, in generate
    return list(self._sampler.generate_prompts(template, num_images))
  File "C:\WEBUI0.65.1\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\samplers\base.py", line 50, in generate_prompts
    command = parse(prompt, parser_config=self._parser_config)
  File "C:\WEBUI0.65.1\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 257, in parse
    tokens = create_parser(parser_config=parser_config).parse_string(
  File "C:\WEBUI0.65.1\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 650), (line:1, col:651)

and 'using version 2.7.3 of the WebUI extension, and the underlying dynamicprompts library is version 0.7.1.'

**Comment by kkmw15** [comment]
i solved the problem via reinstall
