### ISSUE TITLE
MagicPrompt: AssertionError: Torch not compiled with CUDA enabled     

### ISSUE THREAD

**Issue by enzyme69** [adieyal/sd-dynamic-prompts#286]
**Describe the bug**
All dynamic prompting not working for me :(

**To Reproduce**
I used to work, but not anymore. No matter using {red|blue|yellow} or __type__

Also mention which checkboxes have been set.

**Are you using a local install or a colab?**
Local Install.

**Expected behaviour**
It should work and each prompt is dynamic like working months ago.

**Additional context**
ERROR MESSAGE:

1.
```
Error running process: /Users/jimmygunawan/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 412, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 73, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 144, in generate
    return [
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 145, in <listcomp>
    self._generate_magic_prompt(prompt)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 152, in _generate_magic_prompt
    prompt = self._generator(
TypeError: 'NoneType' object is not callable
```

2.
```
First load of MagicPrompt may take a while.
Error running process: /Users/jimmygunawan/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 404, in process
    generator = generator_builder.create_generator()
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/generator_builder.py", line 152, in create_generator
    generator = MagicPromptGenerator(
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 110, in __init__
    self.set_model(model_name)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 138, in set_model
    self._generator = self._load_pipeline(model_name)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 89, in _load_pipeline
    MagicPromptGenerator.generator = pipeline(
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 870, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 64, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 778, in __init__
    self.model = self.model.to(self.device)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1682, in to
    return super().to(*args, **kwargs)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 211, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled               
```

**Comment by enzyme69** [comment]
Quick question, when "saving template to metadata" does it save the original template, or the one that has been dynamically generated?

I am kind suspicious that {prompt1|prompt2|prompt3} might work, as I can see variations, but the prompt metadata is not showing.

**Comment by adieyal** [comment]
Under Settings->Dynamic Prompts, there is a checkbox labelled: `Save template to metadata: Write prompt template into the PNG metadata` - that should be checked.

**Comment by enzyme69** [comment]
I tested and check metadata on PNG, none actually working. CSV saved is also blank, showing "positive prompt" and "negative prompt" on the tab.
![Screenshot 2023-03-04 at 12 54 42 am](https://user-images.githubusercontent.com/3952687/222737765-fa6b28cf-c9fd-4e4e-86d2-48a4fdad83cc.png)

**Comment by adieyal** [comment]
Are you running with Magic Prompt on? Surprisingly that you're getting a CUDA error - what GPU are you running? Also, are you only getting the CUDA error with Magic Prompt? Stable Diffusion will need it as well unless you're generating on your CPU.

**Comment by Artemonim** [comment]
Dynamic Prompt don't work for me too. Error text below:
```py
Error running process: D:\Stable UI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "D:\Stable UI\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\Stable UI\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 412, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "D:\Stable UI\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 83, in generate_prompts
    total_prompts // len(all_negative_prompts) + 1
ZeroDivisionError: integer division or modulo by zero
```

**Comment by enzyme69** [comment]
UPDATE: If I turn of "Magic Prompt" the dynamic prompting seems to work!
