### ISSUE TITLE
Error when generating with prompt magic

### ISSUE THREAD

**Issue by mailani19** [adieyal/sd-dynamic-prompts#302]
**Describe the bug**
Error appears in the cmd window whenever starting to run any generation while magic prompts is turned on

stable-diffusion-webui\venv\lib\site-packages\transformers\pipelines\base.py:1043: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset 
warnings.warn(

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. bot up automatic1111
2. check prompt magic box, 
3. enter in any or even leave black prompt window
4. click generate

Also mention which checkboxes have been set.
dynamic prompts enabled
prompt magic
**Are you using a local install or a colab?**
No
If a colab, which one?
N/A
**Expected behaviour**
It to run without giving an error

**Additional context**
It's with Gustavosa/MagicPrompt-Stable-Diffusion if that bit of info matters.

**Comment by mailani19** [comment]
IT seems to actively be causing SD to run the entire generation process sequentially on the GPU.  Everything is taking about 2-3 times longer to generate after this error happens. and I've only seen it with prompt magic checked.   I've been messing with Automtatic1111 for about 6 weeks now and just installed this extension tonight and just started getting them tonight.  Have not changed anything else except this.

**Comment by 925-Studio** [comment]
I'm facing the same problem except I'm use mac with M1 chips. After download all the files, error message shows in terminal
```
Error running process: /Users/silver/Playgrounds/AI/sdw_1.5/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/Users/silver/Playgrounds/AI/sdw_1.5/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/Users/silver/Playgrounds/AI/sdw_1.5/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 417, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "/Users/silver/Playgrounds/AI/sdw_1.5/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 73, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts) or [""]
  File "/Users/silver/Playgrounds/AI/sdw_1.5/venv-torch-nightly/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 144, in generate
    return [
  File "/Users/silver/Playgrounds/AI/sdw_1.5/venv-torch-nightly/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 145, in <listcomp>
    self._generate_magic_prompt(prompt)
  File "/Users/silver/Playgrounds/AI/sdw_1.5/venv-torch-nightly/lib/python3.10/site-packages/dynamicprompts/generators/magicprompt.py", line 152, in _generate_magic_prompt
    prompt = self._generator(
TypeError: 'NoneType' object is not callable
```

Hope we can get fixed soon. Amazing extension by the way!
