### ISSUE TITLE
Error running process:dynamic_prompting.py

### ISSUE THREAD

**Issue by gihepa988** [adieyal/sd-dynamic-prompts#314]
**Describe the bug**
Script does not work properly when generating images.

**To Reproduce**
Error running process: /storage/stable-diffusion/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 417, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 73, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts) or [""]
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/generators/randomprompt.py", line 46, in generate
    return list(self._context.sample_prompts((template or ""), num_images))
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/samplers/base.py", line 64, in _get_sequence
    yield rotate_and_join(sub_generators, separator=command.separator)
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/utils.py", line 43, in rotate_and_join
    return separator.join(rotate_all(generators))
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/utils.py", line 35, in rotate_all
    return [next(gen) for gen in generators]
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/utils.py", line 35, in <listcomp>
    return [next(gen) for gen in generators]
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/samplers/random.py", line 98, in _get_wildcard
    yield from context.sample_prompts(value, 1)
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/samplers/base.py", line 64, in _get_sequence
    yield rotate_and_join(sub_generators, separator=command.separator)
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/utils.py", line 43, in rotate_and_join
    return separator.join(rotate_all(generators))
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/utils.py", line 35, in rotate_all
    return [next(gen) for gen in generators]
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/utils.py", line 35, in <listcomp>
    return [next(gen) for gen in generators]
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/samplers/random.py", line 65, in _get_variant
    selected_commands = self._get_variant_choices(
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/samplers/random.py", line 28, in _get_variant_choices
    return choose_without_replacement(
  File "/usr/local/lib/python3.9/dist-packages/dynamicprompts/utils.py", line 89, in choose_without_replacement
    chosen = rand.choices(values, weights=weights, k=1)[0]
  File "/usr/lib/python3.9/random.py", line 502, in choices
    raise ValueError('Total of weights must be greater than zero')
ValueError: Total of weights must be greater than zero

colab, on paperspace.

**Additional context**
This may be a rudimentary question, but please answer.

**Comment by adieyal** [comment]
What prompt are you using?

**Comment by akx** [comment]
Closing 🧹
