### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'NoneType'

### ISSUE THREAD

**Issue by Eugenii10** [adieyal/sd-dynamic-prompts#366]
**Describe the bug**
The error message is displayed in the start of generation. Only one image is generated. There is no processing of prompt special characters like `{, }, |`, they are interpretated as plain text.

**To Reproduce**
Prompt:
`({empty masts|no sails|downed sails}:1.3)`

1. Go to 'txt2img.'
2. Enable 'Combinatorial generation'.
3. Enable 'Fixed seed'.
4. Don't change values of 'Batch count', 'Batch size', 'Max generations' and 'Combinatorial batches. They have default values of 1, 1, 0 and 1 respectively.
5. Click 'Generate' button.
6. See error in the console.

```
Error running process: F:\stable-diffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "F:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 449, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 81, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts) or [""]
  File "F:\stable-diffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\frozenprompt_generator.py", line 20, in generate
    return num_images * prompts
TypeError: can't multiply sequence by non-int of type 'NoneType'
```

**What version of the extension and dynamicprompts library do you have installed?**

You are using version 2.10.3 of the WebUI extension, and the underlying dynamicprompts library is version 0.21.2.

**Are you using a local install or a colab?**

Local install of AUTOMATIC1111.

**Expected behaviour**
Three images were generated without any errors. Prompt special characters were treated correctly as combinatorial parts of the prompt.
Bonus: Variation seed (aka subseed) is fixed by the 'Fixed seed' flag of extension.

**Additional context**
Variation seed is not fixing (constant) by flag 'Fixed seed'. It was possible to fix it too by adding next lines in the old (even before 1.0 release) version of extension:
```Python
# dynamic_prompting.py
def process(
# ...
):
  original_subseed = p.subseed
# ...
  all_subseeds = [original_subseed] * updated_count
  p.all_subseeds = all_subseeds
# ...
  p.subseed = original_subseed
```

**Comment by Eugenii10** [comment]
It seems to be connected with the code:
https://github.com/adieyal/sd-dynamic-prompts/blob/b020cb485c6dbdfd82b88f3a799a42180d82dacf/sd_dynamic_prompts/dynamic_prompting.py#L397-L401
And it seems that 'Combinatorial generation' is broken. To generate without error I need to set 'Max generations' value to > 0. Despite of 'Batch count' and/or 'Max generations' values == 3, I got identical three images while having combinatorial generation and fixed seed been enabled.
So there was no point to update extension to the last version for me, since variation seed is not constant there too.

**Comment by adieyal** [comment]
I can't reproduce the error according to your instructions. I can, however, if I set the variation strength to > 0 - it's a minor issue since I don't think what you're trying to do makes sense.

What is your expected output if you ask for variations in combinatorial mode?

**Comment by Eugenii10** [comment]
> What is your expected output if you ask for variations in combinatorial mode?

As in normal mode - get different subvariant of the current seed for an image. The main purpose - to get another image which differs from current but very alike on it.
There is no point to enable Variations and set Variation seed without setting the variation strength > 0. Because if variation strength == 0 then there is no effect of variation seed you will see if I understand right.

**Comment by Eugenii10** [comment]
Well, then I will stay with my current old version. I'm happy with it and my hack. Thanks for your time and explanation! :)
You can close the issue if it will not be fixed (NoneType error).
