### ISSUE TITLE
wild card UI lost... AGAIN...

### ISSUE THREAD

**Issue by vaclav-kyle** [adieyal/sd-dynamic-prompts#369]
Again the problem arises. Of course, I know that this is a colab problem.

Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 14, in <module>
    from dynamicprompts.wildcards import WildcardManager
ModuleNotFoundError: No module named 'dynamicprompts.wildcards'

I executed !git clone https://github.com/Automaticism/Promptvision.git as I knew before, but the error message you see is the message that occurred after executing the code.
The Dynamic Prompt extension is the latest version.
Are there any other things I should check?

![화면 캡처 2023-04-02 132611](https://user-images.githubusercontent.com/128915381/229331302-ac06d3d7-88a0-4187-8eb6-3462716798b2.png)

**Comment by adieyal** [comment]
Have a look at the [troubleshooting section](https://github.com/adieyal/sd-dynamic-prompts#troubleshooting) of the README and see if any of the suggestions work for you.

**Comment by vaclav-kyle** [comment]
> [README의 문제 해결 섹션을](https://github.com/adieyal/sd-dynamic-prompts#troubleshooting) 살펴보고 제안 사항이 있는지 확인하십시오.

oops... sorry. i solve that... BUT!!!

![화면 캡처 2023-04-02 193400](https://user-images.githubusercontent.com/128915381/229347741-d66adca1-d70f-4ef2-b1b4-9f18a0c2e11e.png)
![화면 캡처 2023-04-02 193431](https://user-images.githubusercontent.com/128915381/229347743-d3a65e5e-c603-4899-8ccc-993333988933.png)

**Comment by adieyal** [comment]
weird - did you manually install it? You can probably delete of the folders in the extensions directory

**Comment by vaclav-kyle** [comment]
> weird - did you manually install it? You can probably delete of the folders in the extensions directory

In fact... I can't distinguish which folder is normally working, so I'm just inactive and writing one. haha
