### ISSUE TITLE
ModuleNotFoundError: No module named 'dynamicprompts.wildcardmanager'

### ISSUE THREAD

**Issue by Gushousekai195** [adieyal/sd-dynamic-prompts#389]
I am unable to load WebUI on Colab with Dynamic Prompts.

`Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 13, in <module>
    from dynamicprompts.wildcardmanager import WildcardManager
ModuleNotFoundError: No module named 'dynamicprompts.wildcardmanager'`

**Comment by adieyal** [comment]
Have a look at step three in the troubleshooting section:
[https://github.com/adieyal/sd-dynamic-prompts#troubleshooting](https://github.com/adieyal/sd-dynamic-prompts#troubleshooting)

Let me know if that solves the issue

**Comment by zdoek001** [comment]
> Have a look at step three in the troubleshooting section: https://github.com/adieyal/sd-dynamic-prompts#troubleshooting
> 
> Let me know if that solves the issue

python\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1519, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 20: invalid start byte in RECORD

**Comment by akx** [comment]
@zdoek001 That's an unrelated issue; you have a broken `RECORD` file somewhere in your site-packages.

Anyway, closing this since there hasn't been activity in a while.
