### ISSUE TITLE
Magic Prompt can't run completely locally

### ISSUE THREAD

**Issue by MoodCharge** [adieyal/sd-dynamic-prompts#391]
This extension is really helpful for generating a lot of different prompts. The Magic Prompt feature, which generates new random prompts based on your inputs can not run locally even if I have all the models downloaded. Every time I use any model first time in the Magic Prompt feature on each WebUI instance, I must be online to do so. Could you please fix this?
This is the error information if I run it offline(I have all the models downloaded and ready).
`First load of MagicPrompt may take a while.
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Gustavosta/MagicPrompt-Stable-Diffusion/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))' thrown while requesting HEAD https://huggingface.co/Gustavosta/MagicPrompt-Stable-Diffusion/resolve/main/config.json
Error running process: F:\stable-diffusion-webui-master\extensions\sd-dynamic-prompts-main\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Python3.10.10\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Python3.10.10\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "E:\Python3.10.10\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Gustavosta/MagicPrompt-Stable-Diffusion/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\stable-diffusion-webui-master\extensions\sd-dynamic-prompts-main\sd_dynamic_prompts\dynamic_prompting.py", line 441, in process
    generator = generator_builder.create_generator()
  File "F:\stable-diffusion-webui-master\extensions\sd-dynamic-prompts-main\sd_dynamic_prompts\generator_builder.py", line 163, in create_generator
    generator = MagicPromptGenerator(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\dynamicprompts\generators\magicprompt.py", line 111, in __init__
    self.set_model(model_name)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\dynamicprompts\generators\magicprompt.py", line 141, in set_model
    self._generator = self._load_pipeline(model_name)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\dynamicprompts\generators\magicprompt.py", line 83, in _load_pipeline
    model = AutoModelForCausalLM.from_pretrained(model_name)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 434, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 809, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\transformers\configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\transformers\configuration_utils.py", line 614, in _get_config_dict
    resolved_config_file = cached_file(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\huggingface_hub\file_download.py", line 1166, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\huggingface_hub\file_download.py", line 1498, in get_hf_file_metadata
    r = _request_wrapper(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\huggingface_hub\file_download.py", line 407, in _request_wrapper
    response = _request_wrapper(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\huggingface_hub\file_download.py", line 442, in _request_wrapper
    return http_backoff(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 145, in http_backoff
    raise err
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 129, in http_backoff
    response = requests.request(method=method, url=url, **kwargs)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Gustavosta/MagicPrompt-Stable-Diffusion/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))`

**Comment by adieyal** [comment]
Try setting this environment variable: TRANSFORMERS_OFFLINE=1, let me know if it works

**Comment by akx** [comment]
Closing because no activity in a while.

Also, proxy-related errors are rarely anything we can help with, anyway.
