### ISSUE TITLE
stable diffusion does not start when the network is turned off

### ISSUE THREAD

**Issue by Nik0s5** [adieyal/sd-dynamic-prompts#404]
stable-diffusion-webui does not start after installing sd-dynamic-prompts if there is no network connection, "Installing requirements for Web UI" hangs for several minutes, then an error occurs. If the network is on, then there is no problem. Tested on a clean installed SD.
Extensions:
sd-dynamic-prompts
LDSR	built-in
Lora	built-in
ScuNET	built-in
SwinIR	built-in
prompt-bracket-checker	built-in

```
venv "C:\Users\user\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Traceback (most recent call last):
  File "C:\Users\user\stable-diffusion-webui\launch.py", line 355, in <module>
    prepare_environment()
  File "C:\Users\user\stable-diffusion-webui\launch.py", line 299, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements for Web UI")
  File "C:\Users\user\stable-diffusion-webui\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\Users\user\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "C:\Users\user\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Requirement already satisfied: blendmodes==2022 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 1)) (2022)
Requirement already satisfied: transformers==4.25.1 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 2)) (4.25.1)
Requirement already satisfied: accelerate==0.12.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 3)) (0.12.0)
Requirement already satisfied: basicsr==1.4.2 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 4)) (1.4.2)
Requirement already satisfied: gfpgan==1.3.8 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 5)) (1.3.8)
Requirement already satisfied: gradio==3.23 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 6)) (3.23.0)
Requirement already satisfied: numpy==1.23.3 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 7)) (1.23.3)
Requirement already satisfied: Pillow==9.4.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 8)) (9.4.0)
Requirement already satisfied: realesrgan==0.3.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 9)) (0.3.0)
Requirement already satisfied: torch in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 10)) (1.13.1+cu117)
Requirement already satisfied: omegaconf==2.2.3 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 11)) (2.2.3)
Requirement already satisfied: pytorch_lightning==1.9.4 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 12)) (1.9.4)
Requirement already satisfied: scikit-image==0.19.2 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 13)) (0.19.2)
Requirement already satisfied: fonts in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 14)) (0.0.3)
Requirement already satisfied: font-roboto in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 15)) (0.0.1)
Requirement already satisfied: timm==0.6.7 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 16)) (0.6.7)
Requirement already satisfied: piexif==1.1.3 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 17)) (1.1.3)
Requirement already satisfied: einops==0.4.1 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 18)) (0.4.1)
Requirement already satisfied: jsonmerge==1.8.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 19)) (1.8.0)
Requirement already satisfied: clean-fid==0.1.29 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 20)) (0.1.29)
Requirement already satisfied: resize-right==0.0.2 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 21)) (0.0.2)
Requirement already satisfied: torchdiffeq==0.2.3 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 22)) (0.2.3)
Requirement already satisfied: kornia==0.6.7 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 23)) (0.6.7)
Requirement already satisfied: lark==1.1.2 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 24)) (1.1.2)
Requirement already satisfied: inflection==0.5.1 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 25)) (0.5.1)
Requirement already satisfied: GitPython==3.1.30 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 26)) (3.1.30)
Requirement already satisfied: torchsde==0.2.5 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 27)) (0.2.5)
Requirement already satisfied: safetensors==0.3.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 28)) (0.3.0)
Requirement already satisfied: httpcore<=0.15 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 29)) (0.15.0)
Requirement already satisfied: fastapi==0.94.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from -r requirements_versions.txt (line 30)) (0.94.0)
Requirement already satisfied: aenum<4,>=3.1.7 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from blendmodes==2022->-r requirements_versions.txt (line 1)) (3.1.12)
Requirement already satisfied: deprecation<3,>=2.1.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from blendmodes==2022->-r requirements_versions.txt (line 1)) (2.1.0)
Requirement already satisfied: filelock in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r requirements_versions.txt (line 2)) (3.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r requirements_versions.txt (line 2)) (0.14.0)
Requirement already satisfied: packaging>=20.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r requirements_versions.txt (line 2)) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r requirements_versions.txt (line 2)) (6.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r requirements_versions.txt (line 2)) (2023.3.23)
Requirement already satisfied: requests in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r requirements_versions.txt (line 2)) (2.28.2)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r requirements_versions.txt (line 2)) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r requirements_versions.txt (line 2)) (4.65.0)
Requirement already satisfied: psutil in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.12.0->-r requirements_versions.txt (line 3)) (5.9.5)
Requirement already satisfied: addict in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from basicsr==1.4.2->-r requirements_versions.txt (line 4)) (2.4.0)
Requirement already satisfied: future in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from basicsr==1.4.2->-r requirements_versions.txt (line 4)) (0.18.3)
Requirement already satisfied: lmdb in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from basicsr==1.4.2->-r requirements_versions.txt (line 4)) (1.4.1)
Requirement already satisfied: opencv-python in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from basicsr==1.4.2->-r requirements_versions.txt (line 4)) (4.7.0.72)
Requirement already satisfied: scipy in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from basicsr==1.4.2->-r requirements_versions.txt (line 4)) (1.10.1)
Requirement already satisfied: tb-nightly in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from basicsr==1.4.2->-r requirements_versions.txt (line 4)) (2.13.0a20230424)
Requirement already satisfied: torchvision in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from basicsr==1.4.2->-r requirements_versions.txt (line 4)) (0.14.1+cu117)
Requirement already satisfied: yapf in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from basicsr==1.4.2->-r requirements_versions.txt (line 4)) (0.33.0)
Requirement already satisfied: facexlib>=0.2.5 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gfpgan==1.3.8->-r requirements_versions.txt (line 5)) (0.3.0)
Requirement already satisfied: aiofiles in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (23.1.0)
Requirement already satisfied: aiohttp in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (3.8.4)
Requirement already satisfied: altair>=4.2.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (4.2.2)
Requirement already satisfied: ffmpy in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (0.3.0)
Requirement already satisfied: fsspec in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (2023.4.0)
Requirement already satisfied: httpx in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (0.24.0)
Requirement already satisfied: jinja2 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (3.1.2)
Requirement already satisfied: markdown-it-py[linkify]>=2.0.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (2.2.0)
Requirement already satisfied: markupsafe in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (2.1.2)
Requirement already satisfied: matplotlib in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (3.7.1)
Requirement already satisfied: mdit-py-plugins<=0.3.3 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (0.3.3)
Requirement already satisfied: orjson in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (3.8.10)
Requirement already satisfied: pandas in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (2.0.1)
Requirement already satisfied: pydantic in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (1.10.7)
Requirement already satisfied: pydub in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (0.25.1)
Requirement already satisfied: python-multipart in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (0.0.6)
Requirement already satisfied: semantic-version in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (2.10.0)
Requirement already satisfied: typing-extensions in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (4.5.0)
Requirement already satisfied: uvicorn in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (0.21.1)
Requirement already satisfied: websockets>=10.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from gradio==3.23->-r requirements_versions.txt (line 6)) (11.0.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from omegaconf==2.2.3->-r requirements_versions.txt (line 11)) (4.9.3)
Requirement already satisfied: torchmetrics>=0.7.0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 12)) (0.11.4)
Requirement already satisfied: lightning-utilities>=0.6.0.post0 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 12)) (0.8.0)
Requirement already satisfied: networkx>=2.2 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from scikit-image==0.19.2->-r requirements_versions.txt (line 13)) (3.1)
Requirement already satisfied: imageio>=2.4.1 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from scikit-image==0.19.2->-r requirements_versions.txt (line 13)) (2.28.0)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from scikit-image==0.19.2->-r requirements_versions.txt (line 13)) (2023.4.12)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from scikit-image==0.19.2->-r requirements_versions.txt (line 13)) (1.4.1)
Requirement already satisfied: jsonschema in c:\users\user\stable-diffusion-webui\venv\lib\site-packages (from jsonmerge==1.8.0->-r requirements_versions.txt (line 19)) (4.17.3)
INFO: pip is looking at multiple versions of clean-fid to determine which version is compatible with other requirements. This could take a while.

The conflict is caused by:
    transformers 4.25.1 depends on requests
    basicsr 1.4.2 depends on requests
    gradio 3.23.0 depends on requests
    clean-fid 0.1.29 depends on requests==2.25.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict


stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AE99F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AE9D20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AE9ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AEA080>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AEA230>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AD24A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/clean-fid/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AD3880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/clean-fid/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AD2770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/clean-fid/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AD24D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/clean-fid/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61AE8520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/clean-fid/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A3E1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/realesrgan/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A9C4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/realesrgan/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A9C310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/realesrgan/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A9F910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/realesrgan/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A9ED70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/realesrgan/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A2E2C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gradio/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A2F310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gradio/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A2DA20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gradio/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A2E8F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gradio/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61A2EAA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gradio/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61796920>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gfpgan/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61796A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gfpgan/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61796470>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gfpgan/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB619DA170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gfpgan/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB619DBF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/gfpgan/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB617B3FA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/basicsr/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB617B3610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/basicsr/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB617B1180>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/basicsr/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB617B13C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/basicsr/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB617B26B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/basicsr/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB617692A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB6176B3D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB6176ACB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB61769720>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB6176B4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
ERROR: Cannot install basicsr==1.4.2, clean-fid==0.1.29, gradio==3.23.0 and transformers==4.25.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

with connected network:
```
venv "C:\Users\user\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Installing sd-dynamic-prompts requirements.txt

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [6ce0161689] from C:\Users\user\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\user\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 2.5s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.5s, apply half(): 0.4s, move model to device: 0.4s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 5.8s (import torch: 0.8s, import gradio: 0.6s, import ldm: 0.3s, other imports: 0.5s, load scripts: 0.5s, load SD checkpoint: 2.7s, create ui: 0.2s).
```

**Comment by liuyu-f** [comment]
same error.

When installing requests==2.25.1 according to the prompt, it prompts "dynamic prompts 0.23.0 requires requests<3.0.0,>=2.28.1, but you have requests 2.25.1 which is incompatible.".
But now it works offline, I think it might be a problem of "requests" library version conflict

My English is not good, the above content is translated from Google

**Comment by akx** [comment]
> "dynamic prompts 0.23.0 requires requests<3.0.0,>=2.28.1, but you have requests 2.25.1 which is incompatible."

is a warning, not an error, and you don't need to really care about it.

If you need to start the webui without an internet connection, you can use `webui.py` directly instead of `launch.py`, so it will not do update checks.

Note you may still have issues running the Gradio UI without an internet connection due to upstream issues: https://github.com/gradio-app/gradio/issues/4332
