### ISSUE TITLE
RuntimeError: The expanded size of the tensor (231) must match the existing size (154) at non-singleton dimension 0.

### ISSUE THREAD

**Issue by GreenLandisaLie** [adieyal/sd-dynamic-prompts#413]
Within a batch you can have all sorts of prompts without an issue but the negative prompts seem very sensitive to the number of tokens when they change significantly between each negative prompt **within a batch**.

It was a difficult issue to replicate but you should be able to do so like this:
```
- sampler: DPM++ 2M Karras
- prompt: {A|B}
- negative prompt: {(worst quality:1.2), (low quality:1.2), (bokeh:1.2), (monochrome:1.2), (grayscale:1.2), (greyscale:1.2), (lowres), (text), (speech bubbles), (japanese characters), blurry, sketch, cropped, error, text, extra digit, fewer digits, jpeg artifacts, signature, watermark, username, letterbox, (simple background:1.2), (white background:1.2), (multiple views), bad anatomy, bad hands, missing fingers, (bald), orange hair, blue hair, long blonde hair, yellow eyes, red eyes, pink drill hair, pink twin drills, pink hair, red drill hair, red twin drills, red hair, (black dress:1.1), (grey dress:1.1), (magic circle:1.2)|(worst quality:1.2), (low quality:1.2), (bokeh:1.2), (monochrome:1.2), (grayscale:1.2), (greyscale:1.2), (lowres), (text), (speech bubbles), (japanese characters), blurry, sketch, cropped, error, text, extra digit, fewer digits, jpeg artifacts, signature, watermark, username, letterbox, (simple background:1.2), (white background:1.2), (multiple views), bad anatomy, bad hands, missing fingers, (bald), orange hair, blue hair, long blonde hair, yellow eyes, red eyes, pink drill hair, pink twin drills, pink hair, red drill hair, red twin drills, red hair, (black dress:1.1), (grey dress:1.1), (magic circle:1.2), neck ribbon, pink ribbon, tree, mountain, night sky, plains, yellow smoke, (1boy:1.2), (pink background:1.2), (fog:1.2), (pink smoke:1.2)}
- batch size: 3
- seed: 1
```

Tried to shorten the negative prompt variants (for easier replication) by removing tags in common but for some reason doing so bypassed the error more often than not. Weird issue.

Traceback:
```
Traceback (most recent call last):
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\processing.py", line 635, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\processing.py", line 835, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 351, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 351, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 599, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 88, in forward
    uncond = prompt_parser.reconstruct_cond_batch(uncond, self.step)
  File "C:\SD\AUTO11-ML\stable-diffusion-webui-directml\modules\prompt_parser.py", line 223, in reconstruct_cond_batch
    res[i] = cond_schedule[target_index].cond
RuntimeError: The expanded size of the tensor (231) must match the existing size (154) at non-singleton dimension 0.  Target sizes: [231, 768].  Tensor sizes: [154, 768]
```

Also I believe it is related to: #116

**Comment by spreck** [comment]
I get a similar issue when I have a batch size that is not an integer factor of the number of combinatorial generations.

For example I had 6 options in here {1|2|...|6} and in the gui had the batch count set to 1 and the batch size set to 4.

```
│ C:\Users\spreck\github\automatic\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py:356 in       │
│ q_sample                                                                                                            │
│                                                                                                                     │
│    355 │   │   noise = default(noise, lambda: torch.randn_like(x_start))                                            │
│ >  356 │   │   return (extract_into_tensor(self.sqrt_alphas_cumprod, t, x_start.shape) * x_star                     │
│    357 │   │   │   │   extract_into_tensor(self.sqrt_one_minus_alphas_cumprod, t, x_start.shape                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0
```

However with the exact same 6 options in the {} when I made the batch size 3 then it worked fine and did 1-3 in the first batch and 3-6 in the 2nd batch. I was expecting to get 4 of each with my initial settings but it seems to just cycle through and if the combinatorial batch number doesn't match at some point with the batch size set in the gui it fails.
