### ISSUE TITLE
pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 0), (line:1, col:1)

### ISSUE THREAD

**Issue by YuK1Game** [adieyal/sd-dynamic-prompts#432]
This error occurs when I use an underscore "_" in the prompt. Also, I cannot use wildcards.

I have reinstalled both the extension and site-packages.

```
Error running process: D:\Data\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "D:\Data\AI\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "D:\Data\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 452, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "D:\Data\AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 81, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts) or [""]
  File "D:\Data\AI\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 47, in generate
    return list(self._context.sample_prompts((template or ""), num_images))
  File "D:\Data\AI\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\samplers\random.py", line 117, in _get_wildcard
    yield from context.sample_prompts(value, 1)
  File "D:\Data\AI\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
    command = parse(prompt, parser_config=self.parser_config)
  File "D:\Data\AI\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 454, in parse
    tokens = get_cached_parser(parser_config).parse_string(
  File "D:\Data\AI\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 0), (line:1, col:1)
```

**Comment by akx** [comment]
What was the prompt you tried?

**Comment by akx** [comment]
@Ptibouc77 That doesn't help unless you show us the prompt.

**Comment by akx** [comment]
Closing for now since there wasn't information on the prompt.
