### ISSUE TITLE
Error running process

### ISSUE THREAD

**Issue by syawn07** [adieyal/sd-dynamic-prompts#442]
Error running process: D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "D:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
TypeError: BatchedCombinatorialPromptGenerator.generate() got an unexpected keyword argument 'seeds'

**Comment by ericcartmanfatass** [comment]
the same,after using controlnet hed and color processor,the error came in the console

**Comment by w0lfram** [comment]
Same issue here.

**Comment by adieyal** [comment]
have a look in your terminal, there should be instructions to fix it
