### ISSUE TITLE
Prompting eventually crashes

### ISSUE THREAD

**Issue by Lametastic** [adieyal/sd-dynamic-prompts#458]
After using dynamic prompts for at least a month with no problems whatsoever, in the last 3 days or so I am continually encountering errors. My prompts will work for several iterations, and then suddenly stop completely. Refreshing my browser usually fixes this, but once again only for the next initial batches of images.

I’ve updated everything as far as I can tell, to no avail. I’m getting the following error message every time:

Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\ai\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 449, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "C:\ai\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 71, in generate
    prompts.append(next(iter(gen)))
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\samplers\base.py", line 75, in _get_sequence
    yield rotate_and_join(sub_generators, separator=command.separator)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\utils.py", line 43, in rotate_and_join
    return separator.join(rotate_all(generators))
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\utils.py", line 35, in rotate_all
    return [next(gen) for gen in generators]
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\utils.py", line 35, in <listcomp>
    return [next(gen) for gen in generators]
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\samplers\random.py", line 118, in _get_wildcard
    yield from context.sample_prompts(value, 1)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
    command = parse(prompt, parser_config=self.parser_config)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 454, in parse
    tokens = get_cached_parser(parser_config).parse_string(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '{'  (at char 0), (line:1, col:1)

**Comment by akx** [comment]
You will need to show the prompt you're trying to use - that error is saying the extension can't parse it correctly.

**Comment by Lametastic** [comment]
After much investigation (I have a ton of wildcards), I think I found the problem. Apparently I ended a variant with "]" instead of "}". My bad. What confused me so was that my prompts would work for awhile, and then just stop.

Sorry for the mistake, and thanks for your efforts.

**Comment by adieyal** [comment]
I think this issue can be closed.
