### ISSUE TITLE
Bug fix on the missing logger

### ISSUE THREAD

**Issue by donlinglok** [adieyal/sd-dynamic-prompts#46]
Hi, 

The extension is a masterpiece and I love it.

I am trying to add the `"wildcard_dir":"D:\\wildcards"` in `stable-diffustion-webui/config.json`

but the error shows as below:
```
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\, line 16, in ensure_directory
    self._path.mkdir(parents=True, exist_ok=True)
AttributeError: 'str' object has no attribute 'mkdir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 170, in load
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\y", line 133, in <module>
    wildcard_manager.ensure_directory()
  File "C:\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\, line 18, in ensure_directory
    logger.exception(f"Failed to create directory {self._path}")
NameError: name 'logger' is not defined
```

seems is python missing a logger library. 
```
logger.exception(f"Failed to create directory {self._path}")
======
print (f"Failed to create directory {self._path}")
```
I try to fix it by replacing `logger` with `print`, it works for a while, but error shows in other lines

```
in pick_wildcards
    return re_wildcard.sub(lambda x: self._replace_wildcard(x), template)
  File "C:\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generators\randomprompt.py", line 100, in <lambda>
    return re_wildcard.sub(lambda x: self._replace_wildcard(x), template)
  File "C:\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\generators\randomprompt.py", line 78, in _replace_wildcard
    wildcard_files = self._wildcard_manager.match_files(wildcard)
  File "C:\stable-diffusion-webui\extensions\sd-dynamic-prompts\prompts\wildcardmanager.py", line 33, in match_files
    WildcardFile(path) for path in self._path.rglob(f"{wildcard}.{constants.WILDCARD_SUFFIX}")
AttributeError: 'str' object has no attribute 'rglob'
```

If I use the default WILDCARD_DIR, everything works fine.
May I know can the extension support change wildcard_dir to D:\\ drive?

**Comment by adieyal** [comment]
I'm glad you're enjoying it. Are you using the latest version of the code? The line numbers in your error message don't seem correct.

**Comment by donlinglok** [comment]
> I figured out why it's happening, will post a bug fix in a few minutes

Thank you🎉🎉
