### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by 2x-y** [adieyal/sd-dynamic-prompts#466]
Running with commit [4b4cdc04](https://github.com/adieyal/sd-dynamic-prompts/commit/4b4cdc049fa7ab3ef23504bbb49b37e110f23428) and [v1.3.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/20ae71faa8ef035c31aa3a410b707d792c8203a3) of Automatic1111

On startup I get the following error:

```
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "H:\GitHub\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "H:\GitHub\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\GitHub\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "H:\GitHub\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 12, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
  File "H:\GitHub\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\__init__.py", line 7, in <module>
    from dynamicprompts.generators.jinjagenerator import JinjaGenerator
  File "H:\GitHub\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\jinjagenerator.py", line 14, in <module>    from dynamicprompts.jinja_extensions import DYNAMICPROMPTS_FUNCTIONS, PromptExtension
  File "H:\GitHub\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\jinja_extensions.py", line 8, in <module>
    from jinja2 import Environment, pass_environment
ImportError: cannot import name 'pass_environment' from 'jinja2' (H:\GitHub\stable-diffusion-webui\venv\lib\site-packages\jinja2\__init__.py)
```

I've tried rebuilding the venv folder but that hasn't made any difference.

**Comment by 2x-y** [comment]
I did a "pip install -U jinja2" after activating the venv and it resolved it.
