### ISSUE TITLE
Error loading script: on_app_started.py and Error loading script: packages.py

### ISSUE THREAD

**Issue by Dale007261** [adieyal/sd-dynamic-prompts#470]
Error loading script: on_app_started.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 18, in <module>
    from scripts.packages import get_packages_state, install_package
  File "D:\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\packages.py", line 1, in <module>
    from install import packages
ImportError: cannot import name 'packages' from 'install' (D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\install.py)

Error loading script: packages.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\packages.py", line 1, in <module>
    from install import packages
ImportError: cannot import name 'packages' from 'install' (D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\install.py)

**Comment by adieyal** [comment]
not sure what's happening there, but it looks like its an error coming from sd-webui-prompt-all-in-one

**Comment by adieyal** [comment]
@Dale007261 have you tried to disable sd-webui-prompt-all-in-one to see if that is the cause of the issue?
