### ISSUE TITLE
Error Traceback

### ISSUE THREAD

**Issue by Tobe2d** [adieyal/sd-dynamic-prompts#487]
I am getting this error in the log:

```
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "E:\Ai__Project\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\Ai__Project\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Ai__Project\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "E:\Ai__Project\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 11, in <module>
    from dynamicprompts.generators.promptgenerator import GeneratorException
  File "E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\__init__.py", line 7, in <module>
    from dynamicprompts.generators.jinjagenerator import JinjaGenerator
  File "E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\jinjagenerator.py", line 14, in <module>
    from dynamicprompts.jinja_extensions import DYNAMICPROMPTS_FUNCTIONS, PromptExtension
  File "E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\jinja_extensions.py", line 8, in <module>
    from jinja2 import Environment, pass_environment
ImportError: cannot import name 'pass_environment' from 'jinja2' (E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\jinja2\__init__.py)
```

**Comment by adieyal** [comment]
This issue is a duplicate of https://github.com/adieyal/sd-dynamic-prompts/issues/476 - have a look there for suggestions
