### ISSUE TITLE
TypeError: FeelingLuckyGenerator.generate() got an unexpected keyword argument 'seeds'

### ISSUE THREAD

**Issue by battera** [adieyal/sd-dynamic-prompts#494]
Error running process: H:\sd-webui-aki-v4\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "H:\sd-webui-aki-v4\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "H:\sd-webui-aki-v4\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 449, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "H:\sd-webui-aki-v4\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
  File "H:\sd-webui-aki-v4\py310\lib\site-packages\dynamicprompts\generators\magicprompt.py", line 146, in generate
    prompts = self._prompt_generator.generate(*args, **kwargs)
TypeError: FeelingLuckyGenerator.generate() got an unexpected keyword argument 'seeds'

help！！

**Comment by adieyal** [comment]
Are you using the latest version of the extension?

**Comment by battera** [comment]
> 



> Are you using the latest version of the extension?

I change the the latest version of the extension,but A new error has occurred

Error running install.py for extension H:\sd-webui-aki-v4\extensions\sd-dynamic-prompts.
Command: "H:\sd-webui-aki-v4\py310\python.exe" "H:\sd-webui-aki-v4\extensions\sd-dynamic-prompts\install.py"
Error code: 1
stdout:
stderr: Traceback (most recent call last):

File "H:\sd-webui-aki-v4\extensions\sd-dynamic-prompts\install.py", line 2, in

from sd_dynamic_prompts.version_tools import install_requirements
ModuleNotFoundError: No module named 'sd_dynamic_prompts'
