### ISSUE TITLE
GitCommandError

### ISSUE THREAD

**Issue by Neytiri7** [adieyal/sd-dynamic-prompts#591]
*** Error completing request
*** Arguments: ('', 'https://github.com/adieyal/sd-dynamic-prompts', '') {}
    Traceback (most recent call last):
      File "O:\AI\SynologyDrive\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "O:\AI\SynologyDrive\modules\ui_extensions.py", line 620, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "O:\AI\SynologyDrive\modules\ui_extensions.py", line 357, in install_extension_from_url
        with git.Repo.clone_from(url, tmpdir, filter=['blob:none']) as repo:
      File "O:\AI\SynologyDrive\venv\lib\site-packages\git\repo\base.py", line 1308, in clone_from
        return cls._clone(
      File "O:\AI\SynologyDrive\venv\lib\site-packages\git\repo\base.py", line 1219, in _clone
        finalize_process(proc, stderr=stderr)
      File "O:\AI\SynologyDrive\venv\lib\site-packages\git\util.py", line 419, in finalize_process
        proc.wait(**kwargs)
      File "O:\AI\SynologyDrive\venv\lib\site-packages\git\cmd.py", line 604, in wait
        raise GitCommandError(remove_password_if_present(self.args), status, errstr)
    git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
      cmdline: git clone -v --filter=blob:none -- https://github.com/adieyal/sd-dynamic-prompts O:\AI\SynologyDrive\tmp\sd-dynamic-prompts
      stderr: 'fatal: destination path 'O:\AI\SynologyDrive\tmp\sd-dynamic-prompts' already exists and is not an empty directory.
    '

---

**Comment by akx** [comment]
This is related to `stable-diffusion-webui`'s extension updater, not this extension in particular.

Either way, delete `O:\AI\SynologyDrive\tmp\sd-dynamic-prompts` and try again.

**Comment by Neytiri7** [comment]
It's installed through "cmd", so it's installed normally.

There is a problem with installation with "url".

**Comment by akx** [comment]
Did you try deleting that temporary directory? After all, that's what causing the error:

> fatal: destination path 'O:\AI\SynologyDrive\tmp\sd-dynamic-prompts' already exists and is not an empty directory.

**Comment by Neytiri7** [comment]
The same error was observed on the first installation.

It's installed normally with "CMD" right now, so I'm just going to use it.
