### ISSUE TITLE
LoRA Block Weight error when Dynamic Prompts update to commit 638d4b1

### ISSUE THREAD

**Issue by Array-Cats** [adieyal/sd-dynamic-prompts#593]
Error info

```
Applying attention optimization: xformers... done.
Weights loaded in 8.3s (load weights from disk: 0.4s, apply weights to model: 7.1s, load VAE: 0.2s, move model to device: 0.6s).
*** Error running before_process_batch: W:\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 527, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "W:\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 302, in before_process_batch
        prompts = kwargs["prompts"].copy()
    AttributeError: 'tuple' object has no attribute 'copy'

---
LoRA Block weight (lora): loraA: 0.6 x [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraB: 0.8 x [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraC: 0.8 x [1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:06<00:00,  4.30it/s]
LoRA Block weight (lora): loraA: 0.6 x [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraB: 0.8 x [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
LoRA Block weight (lora): loraC: 0.8 x [1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:09<00:00,  1.62it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 45/45 [00:39<00:00,  1.14it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 45/45 [00:39<00:00,  1.73it/s]
```

Dynamic Prompts commit e53332e work fine.

**Comment by Neverdusk** [comment]
I thought it had to do with LBW too, until I disabled every extension but Dynamic Prompts and got the same error. To test, my prompt was only the word "masterpiece" with no negative prompt. No wildcards invoked or anything, and generation completely failed. Then I remove Dynamic Prompts and everything works perfectly.

Dynamic Prompts seems to be preventing _any_ kind of generation at the moment, just by being enabled.

Here's my error:

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.49it/s]
*** Error completing request███████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.81it/s]
*** Arguments: ('task(uxh4eg056p0m8gf)', 'masterpiece', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x0000022D7F300C10>, 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "C:\Users\silve\Documents\AI Art\__SDUX_Test\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\silve\Documents\AI Art\__SDUX_Test\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\Users\silve\Documents\AI Art\__SDUX_Test\modules\txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\silve\Documents\AI Art\__SDUX_Test\modules\processing.py", line 673, in process_images
        res = process_images_inner(p)
      File "C:\Users\silve\Documents\AI Art\__SDUX_Test\modules\processing.py", line 866, in process_images_inner
        text = infotext(n, i)
      File "C:\Users\silve\Documents\AI Art\__SDUX_Test\modules\processing.py", line 726, in infotext
        all_prompts[iteration * p.batch_size:(iteration + 1) * p.batch_size] = p.prompts
    TypeError: 'tuple' object does not support item assignment

---

**Comment by katana-hydra** [comment]
I also encountered this problem, please fix it as soon as possible.

**Comment by AIrtistry** [comment]
the extension is completely broken at this moment

**Comment by Neverdusk** [comment]
The newest update seems to work perfectly for me now, with and without LBW enabled - at least from the test generations I've done.

**Comment by adieyal** [comment]
@AIrtistry @katana-hydra @Array-Cats Can you confirm what @Neverdusk is seeing? Is this still an issue?

**Comment by akx** [comment]
Tuples don't have item assignment or `.copy()` – we'll need to make sure the extension doesn't inadvertently cast them to lists.

**Comment by akx** [comment]
#597 will add tests to better cover the processing script.
