### ISSUE TITLE
TypeError: zip() takes no keyword arguments

### ISSUE THREAD

**Issue by heiyumiao** [adieyal/sd-dynamic-prompts#601]
help!
How to fix this bug.

*** Error running process: /home/1/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
    Traceback (most recent call last):
      File "/home/1/stable-diffusion-webui/modules/scripts.py", line 519, in process
        script.process(p, *script_args)
      File "/home/1/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 470, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "/home/1/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/helpers.py", line 104, in generate_prompts
        return generate_prompt_cross_product(all_prompts, all_negative_prompts)
      File "/home/1/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/helpers.py", line 128, in generate_prompt_cross_product
        zip(*product(prompts, negative_prompts), strict=True),
    TypeError: zip() takes no keyword arguments

**Comment by akx** [comment]
You're probably using an older Python version than we support. You should use 3.10 or newer.

**Comment by heiyumiao** [comment]
Thank you for your help! 
I'm using Python 3.9.
So, besides upgrading, are there any other ways?

**Comment by akx** [comment]
Python 3.9 compatibility should be restored (in this aspect) with #602. However, you should know the upstream stable-diffusion-webui repository does not officially support Python 3.9 any longer, so you should upgrade.

**Comment by heiyumiao** [comment]
Thank you for the update. It's great to hear that the compatibility with Python 3.9 has been restored through issue #602. However, Given the lack of official support, it seems wise to follow your advice and upgrade to a newer Python version that is officially supported. 
Thanks again for your valuable input!
