### ISSUE TITLE
can not work dynamic prompts

### ISSUE THREAD

**Issue by Masakki55** [adieyal/sd-dynamic-prompts#603]
Hello. Please help me.
How to fix the below?

    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 794, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1051, in sample
        raise Exception(f"could not find upscaler named {self.hr_upscaler}")
    Exception: could not find upscaler named SwinIR 4x

**Comment by Masakki55** [comment]
<img width="1190" alt="Screenshot 2023-08-23 at 5 43 10 AM" src="https://github.com/adieyal/sd-dynamic-prompts/assets/142944530/e6317e0e-3733-452b-ab6c-e059fcd771f9">
<img width="1092" alt="Screenshot 2023-08-23 at 5 44 07 AM" src="https://github.com/adieyal/sd-dynamic-prompts/assets/142944530/8d2499dd-d820-4861-8db5-ea9d26ad319c">
