### ISSUE TITLE
dynamic-prompts can not work

### ISSUE THREAD

**Issue by Masakki55** [adieyal/sd-dynamic-prompts#604]
Hello, please help me.
How to fix it
<img width="598" alt="Screenshot 2023-08-23 at 6 20 31 AM" src="https://github.com/adieyal/sd-dynamic-prompts/assets/142944530/5f194038-8b37-42e3-b702-355a8544317b">

I set Max generation to "5" but only 1 image was generated.

Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 519, in process
        script.process(p, *script_args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 470, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/generators/batched_combinatorial.py", line 25, in generate
        images.extend(self._generator.generate(template, max_prompts, **kwargs))
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/generators/combinatorial.py", line 37, in generate
        self._context.sample_prompts((template or ""), max_prompts),
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/parser/parse.py", line 454, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "/usr/local/lib/python3.10/dist-packages/pyparsing/core.py", line 1197, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 260), (line:1, col:261)

**Comment by adieyal** [comment]
could you please provide your prompt?

**Comment by Masakki55** [comment]
Thank you, boss.
As you guess, my prompt wildcard is wrong as __haircolor
I change __hairclolor__ then works.

dynamic-prompts is an excellent tool, thank you.
