### ISSUE TITLE
"StopIteration" Console Error when using no prompt (Re: Controlnet models with functions that work w/o a txt prompt)

### ISSUE THREAD

**Issue by CCpt5** [adieyal/sd-dynamic-prompts#629]
Hello,

This may be a non-important warning/error but I don't recall seeing it in the past so I wanted to mention. When generating images in TXT2IMG or IMG2IMG w/o a prompt I'm getting seeing the following error in the console. It doesn't not stop/affect generating though.

```
100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:01<00:00, 22.73it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:01<00:00, 27.19it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:01<00:00, 27.22it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:01<00:00, 27.18it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████| 132/132 [00:05<00:00, 22.24it/s]
*** Error running process: D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\extensions\a1-sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\extensions\a1-sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 485, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\extensions\a1-sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "D:\Stable-Diffusion-Webui-Dev\sdxl\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 71, in generate
        prompts.append(next(iter(gen)))
    StopIteration
```

Some controlnet models like Inpainting and the newer "Revision" have functions that guess if no prompt is entered - Thus "no prompt" is a valid entry in those cases.

**Comment by dmower16** [comment]
Same error happens when using the inpaint tab with no prompt. Opening the dynamic prompts section and unchecking the 'Dynamic prompts enabled' box will prevent the error but it's always enabled by default so this error gets rather annoying.

Maybe it could silently fail if there's nothing in the prompt?
