### ISSUE TITLE
dynamic prompts not loading at all

### ISSUE THREAD

**Issue by ello222** [adieyal/sd-dynamic-prompts#631]
I've recently reinstalled stable diffusion on runpod and after installing dynamic prompts it appears the extension is not being loaded at all. 

Under extension the dynamic prompt is ticked and appeared to be installed but the banner that usually appears under controlnet in txt2img is not showing and the settings for dynamic prompts is not showing either the wildcard section is missing also.

I've created multiple pods to makes sure that it wasn't installation bug issue and they all seem to be acting the same way. Not sure if anyone else is facing the same issue.

**Comment by ello222** [comment]
actually i found this when starting webui:

*** Error loading script: dynamic_prompting.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 3, in <module>
        from sd_dynamic_prompts.dynamic_prompting import Script
      File "/workspace/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 8, in <module>
        import dynamicprompts
    ModuleNotFoundError: No module named 'dynamicprompts'

**Comment by ello222** [comment]
i found the solution here:

https://github.com/adieyal/sd-dynamic-prompts/issues/353
