### ISSUE TITLE
Dynamic Prompts Isn't working

### ISSUE THREAD

**Issue by TypicalZedF** [adieyal/sd-dynamic-prompts#649]
No idea why, but I'm getting this Error when using Dynamic Prompts after a fresh install.

```
*** Error running process: D:\AI\Stable Diffusion AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "D:\AI\Stable Diffusion AI\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\AI\Stable Diffusion AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 485, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "D:\AI\Stable Diffusion AI\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "D:\AI\Stable Diffusion AI\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 71, in generate
        prompts.append(next(iter(gen)))
    StopIteration

---
```

**Comment by esqanor** [comment]
same problem here

**Comment by akx** [comment]
What prompt are you using? What are your settings, etc.?

**Comment by TheLounger** [comment]
Seems to happen when prompt is empty.
Negative prompt, or any other settings/model don't seem to matter.

stable-diffusion-webui dev [v1.6.0-400-gf0f100e6](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f0f100e67b78f686dc73cf3c8cad422e45cc9b8a)
sd-dynamic-prompts [aedb3e4b](https://github.com/adieyal/sd-dynamic-prompts/commit/aedb3e4b91026351981f8412eb9e2e74167fdcff)

**Comment by silveroxides** [comment]
> I get the same error as above when prompt is empty. Typing even just one letter in the prompt and the error goes away. Negative prompt, or any other settings/model don't seem to matter.
> 
> stable-diffusion-webui dev [v1.6.0-400-gf0f100e6](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f0f100e67b78f686dc73cf3c8cad422e45cc9b8a) sd-dynamic-prompts [aedb3e4b](https://github.com/adieyal/sd-dynamic-prompts/commit/aedb3e4b91026351981f8412eb9e2e74167fdcff)

For real? It freaks out because of nothing in text boxes? Cause for me it freaked out from the built-in script that comes with by default called img2imgalt when I had not filled in prompt.

**Comment by MrMxyzptlk** [comment]
Ditto when I have empty prompts...
