### ISSUE TITLE
can't use magical prompts

### ISSUE THREAD

**Issue by 2575044704** [adieyal/sd-dynamic-prompts#675]
WARNING:dynamicprompts.generators.magicprompt:First load of MagicPrompt may take a while.
*** Error running process: /mnt/workspace/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 417, in cached_file
        resolved_file = hf_hub_download(
      File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
        raise LocalEntryNotFoundError(
    huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/mnt/workspace/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/mnt/workspace/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 466, in process
        generator = generator_builder.create_generator()
      File "/mnt/workspace/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/generator_builder.py", line 163, in create_generator
        generator = MagicPromptGenerator(
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/generators/magicprompt.py", line 127, in __init__
        self.set_model(model_name)
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/generators/magicprompt.py", line 157, in set_model
        self._generator = self._load_pipeline(model_name)
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/generators/magicprompt.py", line 86, in _load_pipeline
        tokenizer = AutoTokenizer.from_pretrained(model_name)
      File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained
        config = AutoConfig.from_pretrained(
      File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 944, in from_pretrained
        config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 574, in get_config_dict
        config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
        resolved_config_file = cached_file(
      File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 452, in cached_file
        raise EnvironmentError(
    OSError: We couldn't connect to 'https://huggingface.co/' to load this file, couldn't find it in the cached files and it looks like FredZhang7/anime-anything-promptgen-v2 is not the path to a directory containing a file named config.json.
    Checkout your internet connection o

**Comment by akx** [comment]
> We couldn't connect to 'https://huggingface.co/' to load this file

We can't really help you with a connection issue, I'm afraid. If you're in a location that has a restrictive firewall, you will probably need to figure out how to bypass it.

**Comment by 2575044704** [comment]
> > We couldn't connect to 'https://huggingface.co/' to load this file
> 
> We can't really help you with a connection issue, I'm afraid. If you're in a location that has a restrictive firewall, you will probably need to figure out how to bypass it.

where can I download the file? I want a download link so that I will manually download and upload to my server. My server blocks the a lot of non-chinese websites, unfortunately.

**Comment by akx** [comment]
https://huggingface.co/FredZhang7/anime-anything-promptgen-v2/tree/main is the source for that particular model.
