### ISSUE TITLE
An error message is suddenly being displayed.

### ISSUE THREAD

**Issue by Neytiri7** [adieyal/sd-dynamic-prompts#698]
```
*** Error running process: O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "O:\AI\SynologyDrive\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 481, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 67, in generate
        gen = self._context.sample_prompts(template, num_images)
      File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 454, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "O:\AI\SynologyDrive\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1197, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '{'  (at char 308), (line:7, col:2)
```

**Comment by akx** [comment]
Your prompt has a syntax error. We can't help without seeing the prompt.

**Comment by Neytiri7** [comment]
I solved it.
"ui-config" must have been twisted while playing git switch.
It was restored by erasing and backing up the old one.
