### ISSUE TITLE
It's can't work.

### ISSUE THREAD

**Issue by xlibfly** [adieyal/sd-dynamic-prompts#742]
To create a public link, set `share=True` in `launch()`.
2024-03-17 17:12:04,083 - AnimateDiff - INFO - Hacking i2i-batch is already done.
2024-03-17 17:12:04,086 - AnimateDiff - INFO - Hacking i2i-batch is already done.
Startup time: 71.1s (prepare environment: 29.0s, import torch: 10.5s, import gradio: 1.0s, setup paths: 0.6s, initialize shared: 0.3s, other imports: 0.5s, list SD models: 0.3s, load scripts: 8.7s, create ui: 7.3s, gradio launch: 0.8s, add APIs: 11.7s, app_started_callback: 0.3s).
*** Error running process: D:\sd-webui-aki-v4.5\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.5\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "D:\sd-webui-aki-v4.5\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 481, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "D:\sd-webui-aki-v4.5\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 71, in generate
        prompts.append(str(next(iter(gen))))
    StopIteration

---

please help！it's can't work.

**Comment by akx** [comment]
You need to show the prompt you've tried, we can't help otherwise.
