### ISSUE TITLE
Parse exception when using %

### ISSUE THREAD

**Issue by jonthansen** [adieyal/sd-dynamic-prompts#750]
Describe the bug:

Using a percent sign (%) anywhere in the prompt produces a parse exception. It appears related to a (new?) wrap command. I cannot find any documentation for the wrap command and this exception now prevents any other extensions or scripts from using the percent sign without breaking Dynamic Prompts. This has always been the case for the dollar sign ($).

*** Error running process: X:\Automatic1111\webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "X:\Automatic1111\webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "X:\Automatic1111\webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 481, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "X:\Automatic1111\webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "X:\Automatic1111\webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 67, in generate
        gen = self._context.sample_prompts(template, num_images)
      File "X:\Automatic1111\webui\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "X:\Automatic1111\webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 557, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "X:\Automatic1111\webui\venv\lib\site-packages\pyparsing\core.py", line 1197, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '%'  (at char 0), (line:1, col:1)

Local Install, Version 2.17.1 of the WebUI extension, dynamicprompts library Version 0.31.0

Expected behavior:

Parsing of percent and dollar signs not conforming to Dynamic Prompts syntax should be handled gracefully, leaving them in place, and allowing Dynamic Prompts to continue without the exception

**Comment by akx** [comment]
Please show the prompt you're using.

You're right the wrap command is new; it's documented [here](https://github.com/adieyal/dynamicprompts/blob/main/docs/SYNTAX.md#wrap-command).
