### ISSUE TITLE
not working with a1111 dev branch

### ISSUE THREAD

**Issue by asdnemasd** [adieyal/sd-dynamic-prompts#752]
`*** Error running process: C:\xaxs\stable-diffusion-webui-dev\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "C:\xaxs\stable-diffusion-webui-dev\modules\scripts.py", line 820, in process
        script.process(p, *script_args)
      File "C:\xaxs\stable-diffusion-webui-dev\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 372, in process
        ignore_whitespace = opts.dp_ignore_whitespace
      File "C:\xaxs\stable-diffusion-webui-dev\modules\options.py", line 142, in __getattr__
        return super(Options, self).__getattribute__(item)
    AttributeError: 'Options' object has no attribute 'dp_ignore_whitespace'`

**Comment by akx** [comment]
See #754. This should be fixed by #760.
