### ISSUE TITLE
Conflict with embedding-merge after 1567e787

### ISSUE THREAD

**Issue by miasik** [adieyal/sd-dynamic-prompts#761]
I often use the construction:
`[<'__celeb-female__'>|<'__celeb-female__'>|<'__celeb-female__'>]`
this image can be used as an example of a working case: https://civitai.com/images/8978341
and before #[1567e787](https://github.com/adieyal/sd-dynamic-prompts/commit/1567e7871a703ab7359a95e3d33fcbd708ce890b) it worked without any problem
Now I see an error from [embedding merger](https://github.com/klimaleksus/stable-diffusion-webui-embedding-merge) 

> Traceback (most recent call last):
>       File "E:\SD\automatic1111\modules\processing.py", line 785, in process_images
>         res = process_images_inner(p)
>       File "E:\SD\automatic1111\modules\processing.py", line 853, in process_images_inner
>         with torch.no_grad(), p.sd_model.ema_scope():
>       File "E:\SD\automatic1111\extensions\stable-diffusion-webui-embedding-merge\scripts\embedding_merge.py", line 1197, in __getattribute__
>         raise Exception_From_EmbeddingMergeExtension(msg)
>     embedding_merge.py._webui_embedding_merge_.<locals>.Exception_From_EmbeddingMergeExtension:
> 
>     Embedding Merge failed - Not found closing ">" after "<'"
> 
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "E:\SD\automatic1111\modules\txt2img.py", line 110, in txt2img
>         processed = processing.process_images(p)
>       File "E:\SD\automatic1111\modules\processing.py", line 788, in process_images
>         sd_models.apply_token_merging(p.sd_model, 0)
>       File "E:\SD\automatic1111\extensions\stable-diffusion-webui-embedding-merge\scripts\embedding_merge.py", line 1197, in __getattribute__
>         raise Exception_From_EmbeddingMergeExtension(msg)
>     embedding_merge.py._webui_embedding_merge_.<locals>.Exception_From_EmbeddingMergeExtension:
> 
>     Embedding Merge failed - Not found closing ">" after "<'"
> 
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "E:\SD\automatic1111\modules\call_queue.py", line 57, in f
>         res = list(func(*args, **kwargs))
>       File "E:\SD\automatic1111\modules\call_queue.py", line 36, in f
>         res = func(*args, **kwargs)
>       File "E:\SD\automatic1111\modules\txt2img.py", line 106, in txt2img
>         with closing(p):
>       File "C:\Users\miasik\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 340, in __exit__
>         self.thing.close()
>       File "E:\SD\automatic1111\extensions\stable-diffusion-webui-embedding-merge\scripts\embedding_merge.py", line 1197, in __getattribute__
>         raise Exception_From_EmbeddingMergeExtension(msg)
>     embedding_merge.py._webui_embedding_merge_.<locals>.Exception_From_EmbeddingMergeExtension:
> 
>     Embedding Merge failed - Not found closing ">" after "<'"
> 

As for me it looks like DP started eating some symbols.

**Comment by miasik** [comment]
Something happened and it works now.
