### ISSUE TITLE
I'm Feeling Lucky / 524 Server Error

### ISSUE THREAD

**Issue by androideve** [adieyal/sd-dynamic-prompts#768]
I'm using sd-dynamic-prompts latest commit 1567e78 and comfyui latest commit 27d5808.

When using the "I'm feeling lucky" node, I get the following error message:

```
Requesting https://lexica.art/api/v1/search?q=A mech warrior
Error while generating prompt: 524 Server Error:  for url: https://lexica.art/api/v1/search?q=A%20mech%20warrior
Traceback (most recent call last):
  File "D:\ai\ComfyUI_windows_portable\python_embeded\lib\site-packages\dynamicprompts\generators\feelinglucky.py", line 49, in generate
    data = query_lexica(query)
  File "D:\ai\ComfyUI_windows_portable\python_embeded\lib\site-packages\dynamicprompts\generators\feelinglucky.py", line 27, in query_lexica
    response.raise_for_status()
  File "D:\ai\ComfyUI_windows_portable\python_embeded\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 524 Server Error:  for url: https://lexica.art/api/v1/search?q=A%20mech%20warrior

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts\nodes\feeling_lucky.py", line 32, in get_prompt
    prompt = self._prompt_generator.generate(text, 1)[0]
  File "D:\ai\ComfyUI_windows_portable\python_embeded\lib\site-packages\dynamicprompts\generators\feelinglucky.py", line 54, in generate
    raise GeneratorException(f"Error while generating prompt: {e}") from e
dynamicprompts.generators.promptgenerator.GeneratorException: Error while generating prompt: 524 Server Error:  for url: https://lexica.art/api/v1/search?q=A%20mech%20warrior
```

**Comment by androideve** [comment]
mistakenly made this issue with the webui version
