### ISSUE TITLE
Issue with dynamic prompts & extra networks

### ISSUE THREAD

**Issue by Firestorm007** [adieyal/sd-dynamic-prompts#770]
I'm recently getting an issue with using dynamic prompts with extra networks such as loras. Not every generation, but fairly frequently it causes the extra networks to fail to load in correctly so that they are not applied and this massively slows the generation down for this image and the next and then it recovers. 
I'm using the latest version of forge. Please see error below, can anyone help?

Traceback (most recent call last):
  File "C:\Users\lukeg\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 56, in load_networks
    net = load_network(name, network_on_disk)
  File "C:\Users\lukeg\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 31, in load_network
    net.mtime = os.path.getmtime(network_on_disk.filename)
AttributeError: 'NoneType' object has no attribute 'filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lukeg\stable-diffusion-webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\Users\lukeg\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\Users\lukeg\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 58, in load_networks
    errors.display(e, f"loading network {network_on_disk.filename}")
AttributeError: 'NoneType' object has no attribute 'filename'

**Comment by Hunt3rseeker** [comment]
I'm also getting this error on the latest version of Forge.

**Comment by nguyri** [comment]
If your Lora has "__" in the name the dynamic prompts and wildcards extensions are expecting a wildcard and get confused. 

Checked here, last one says to rename so I tried it and it worked
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1888
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13561

Error looks like this in dynamic prompts
pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 189), (line:1, col:190)

Error looks something like this in wildcards
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001337A1AD450>]: AttributeError
