### ISSUE TITLE
Since the recent update : randomprompt.py", line 10, 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Extraltodeus** [adieyal/sd-dynamic-prompts#79]
Running in a fresh colab install (at start of the webui).

Would you need more informations?

```
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/dynamic-prompts/scripts/dynamic_prompting.py", line 18, in <module>
    from prompts.generators import (
  File "/content/stable-diffusion-webui/extensions/dynamic-prompts/prompts/generators/__init__.py", line 13, in <module>
    from .randomprompt import RandomPromptGenerator
  File "/content/stable-diffusion-webui/extensions/dynamic-prompts/prompts/generators/randomprompt.py", line 10, in <module>
    variant_range = tuple[int, int]
TypeError: 'type' object is not subscriptable
```

**Comment by PcMacsterRace** [comment]
Exact same issue happening to me as well. Same error as well.

**Comment by adieyal** [comment]
Should be fixed now - you're probably using a slightly older version of python

**Comment by Extraltodeus** [comment]
Yeah I don't remember the version that google colab uses but I know that it's an older one indeed.
