### ISSUE TITLE
Error running process

### ISSUE THREAD

**Issue by kvsh88** [adieyal/sd-dynamic-prompts#799]
Hello I am getting the Following error while running Dynamic prompts

Error running process: E:\Program Files\Stable Diffusion\sd.webui\webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "E:\Program Files\Stable Diffusion\sd.webui\webui\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "E:\Program Files\Stable Diffusion\sd.webui\webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 480, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "E:\Program Files\Stable Diffusion\sd.webui\webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "E:\Program Files\Stable Diffusion\sd.webui\system\python\lib\site-packages\dynamicprompts\generators\batched_combinatorial.py", line 25, in generate
        images.extend(self._generator.generate(template, max_prompts, **kwargs))
      File "E:\Program Files\Stable Diffusion\sd.webui\system\python\lib\site-packages\dynamicprompts\generators\combinatorial.py", line 37, in generate
        str(p) for p in self._context.sample_prompts((template or ""), max_prompts)
      File "E:\Program Files\Stable Diffusion\sd.webui\system\python\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "E:\Program Files\Stable Diffusion\sd.webui\system\python\lib\site-packages\dynamicprompts\parser\parse.py", line 557, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "E:\Program Files\Stable Diffusion\sd.webui\system\python\lib\site-packages\pyparsing\core.py", line 1200, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 964), (line:6, col:297)

Could Someone point me on how to diagnose the issue ?

**Comment by nsby7c** [comment]
Same issue here and I haven't found a solution all afternoon

**Comment by popsoda27** [comment]
Same here. No matter which wildcard I use.

*** Error running process: E:\Downloads\stable-diffusion-webui-directml\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "E:\Downloads\stable-diffusion-webui-directml\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "E:\Downloads\stable-diffusion-webui-directml\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 480, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "E:\Downloads\stable-diffusion-webui-directml\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 97, in generate_prompts
        all_negative_prompts = negative_prompt_generator.generate(
      File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 67, in generate
        gen = self._context.sample_prompts(template, num_images)
      File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 557, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\pyparsing\core.py", line 1200, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 24), (line:1, col:25)

**Comment by akx** [comment]
Whenever you get "pyparsing.exceptions.ParseException", it means there's something wrong with your prompt syntax. Without seeing the exact prompt, there is no way we can help with these.

**Comment by A-Null-Fissure** [comment]
I was having a very similar error (not sure if identical), my problem was that someone had a double underscore "__" in a lora name and it broke all the wildcards it was in.

**Comment by Diffus3d** [comment]
To add to this, I had the same problem because a lora being referenced in a wildcard had "!$@" it its prompts, which errored things out.  Removing that part of the lora prompt fixed the issue.

**Comment by alexdisablo** [comment]
> I was having a very similar error (not sure if identical), my problem was that someone had a double underscore "__" in a lora name and it broke all the wildcards it was in.

THANK YOU! I had the same problem and couldn't figure out what was causing it. It appears that was LORA with __ in the name. I changed the Lora display name to filename in settings and now it works.
