### ISSUE TITLE
wildcards not working... parsing error

### ISSUE THREAD

**Issue by Thawtz** [adieyal/sd-dynamic-prompts#811]
automatic1111 is not recognizing dynamic prompts wildcard folder.  a parsing error keeps popping up:

*** Error running process: F:\Stable Diffusion\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "F:\Stable Diffusion\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "F:\Stable Diffusion\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 480, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "F:\Stable Diffusion\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 97, in generate_prompts
        all_negative_prompts = negative_prompt_generator.generate(
      File "F:\Stable Diffusion\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 67, in generate
        gen = self._context.sample_prompts(template, num_images)
      File "F:\Stable Diffusion\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "F:\Stable Diffusion\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 557, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "F:\Stable Diffusion\venv\lib\site-packages\pyparsing\core.py", line 1200, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '%'  (at char 39), (line:1, col:40)

**Comment by Thawtz** [comment]
think i figured it out on my end.
