### ISSUE TITLE
Dynamic prompts stopped working

### ISSUE THREAD

**Issue by bigmantingzz** [adieyal/sd-dynamic-prompts#832]
They were working fine yesterday but today they dont work.  Deleting and redownloading didnt seem to help.This is the error i get. Theres nothing wrong with the prompt ive reused the same one that worked yesterday to check, and even basic stuff like "1girl, { red | blue } hair " doesnt work. The images that get generated also dont load their preview. Need help ;(
 
 *** Error running process: E:\a1111\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "E:\a1111\stable-diffusion-webui\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "E:\a1111\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 480, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "E:\a1111\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "E:\a1111\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 67, in generate
        gen = self._context.sample_prompts(template, num_images)
      File "E:\a1111\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "E:\a1111\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 557, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "E:\a1111\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1216, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 262), (line:3, col:33)

**Comment by bigmantingzz** [comment]
well im not sure if its fixed now but i got rid of the error by removing 1 specific lora i was using and it started working again, any ideas why? that one specific lora is kindof pivotal for me aswell unfortunately

**Comment by bigmantingzz** [comment]
solved: it was caused by the lora having 2 underscores in their name, renaming lora fixed it
