### ISSUE TITLE
"error" message.

### ISSUE THREAD

**Issue by yami-no-tusbas** [adieyal/sd-dynamic-prompts#92]
**Describe the bug**
An error pop's up.

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. Go to wildcards manager tab
2. Click on 'any wildcard found'

```Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\sd-dynamic-prompts\ui\wildcards_tab.py", line 106, in receive_tree_event
    path = wildcard_manager.wildcard_to_path(js["name"])
AttributeError: 'WildcardManager' object has no attribute 'wildcard_to_path'``

https://i.imgur.com/dJqXPGk.png

**Expected behaviour**
No error and be able to see the text, maybe even edit it.

**Comment by adieyal** [comment]
Thanks for reporting this - it's a strange error because it is complaining about something missing which is definitely there. Have you restarted the webui since you updated the extension?
